// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state10 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_read;
input  [31:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond461_i_reg_2605;
reg   [0:0] exitcond461_i_reg_2605_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_2614;
reg   [0:0] or_cond_i_i_reg_2614_pp0_iter1_reg;
reg   [0:0] icmp_reg_2538;
reg   [0:0] tmp_4_reg_2533;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] or_cond_i_reg_2637;
reg   [0:0] or_cond_i_reg_2637_pp0_iter3_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [31:0] t_V_2_reg_530;
wire   [1:0] tmp_6_fu_541_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] tmp_s_fu_553_p2;
reg   [31:0] tmp_s_reg_2491;
wire   [0:0] tmp_7_fu_547_p2;
wire   [31:0] tmp_1_fu_558_p2;
reg   [31:0] tmp_1_reg_2496;
wire   [31:0] p_neg466_i_fu_563_p2;
reg   [31:0] p_neg466_i_reg_2501;
wire   [31:0] tmp_8_fu_568_p2;
reg   [31:0] tmp_8_reg_2508;
wire   [31:0] tmp_9_fu_578_p2;
reg   [31:0] tmp_9_reg_2513;
wire   [31:0] tmp_65_2_fu_589_p2;
reg   [31:0] tmp_65_2_reg_2520;
wire   [31:0] i_V_fu_600_p2;
reg   [31:0] i_V_reg_2528;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_4_fu_606_p2;
wire   [0:0] exitcond462_i_fu_595_p2;
wire   [0:0] icmp_fu_621_p2;
wire   [0:0] tmp_11_fu_627_p2;
reg   [0:0] tmp_11_reg_2543;
wire   [0:0] tmp_113_0_1_fu_633_p2;
reg   [0:0] tmp_113_0_1_reg_2547;
wire   [0:0] tmp_12_fu_639_p2;
reg   [0:0] tmp_12_reg_2551;
wire   [31:0] y_fu_841_p3;
reg   [31:0] y_reg_2564;
wire   [31:0] y_0_1_fu_857_p3;
reg   [31:0] y_0_1_reg_2569;
wire   [31:0] y_0_2_fu_873_p3;
reg   [31:0] y_0_2_reg_2574;
wire   [0:0] tmp_69_0_0_not_fu_881_p2;
reg   [0:0] tmp_69_0_0_not_reg_2579;
wire    ap_CS_fsm_state4;
wire   [1:0] tmp_24_fu_890_p1;
reg   [1:0] tmp_24_reg_2584;
wire   [1:0] tmp_33_fu_898_p1;
reg   [1:0] tmp_33_reg_2591;
wire   [1:0] tmp_34_fu_906_p1;
reg   [1:0] tmp_34_reg_2598;
wire   [0:0] exitcond461_i_fu_910_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
reg    ap_predicate_op226_read_state7;
reg    ap_predicate_op238_read_state7;
reg    ap_predicate_op268_read_state7;
reg    ap_predicate_op280_read_state7;
reg    ap_predicate_op307_read_state7;
reg    ap_predicate_op316_read_state7;
reg    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
reg    ap_block_state9_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond461_i_reg_2605_pp0_iter2_reg;
wire   [31:0] j_V_fu_915_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_962_p2;
wire   [31:0] x_fu_1008_p3;
reg   [31:0] x_reg_2618;
wire   [0:0] brmerge_fu_1016_p2;
reg   [0:0] brmerge_reg_2624;
reg   [0:0] brmerge_reg_2624_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_1021_p2;
reg   [0:0] or_cond_i_reg_2637_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_2637_pp0_iter2_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_2641;
wire   [1:0] tmp_45_fu_1042_p1;
reg   [1:0] tmp_45_reg_2647;
reg   [10:0] k_buf_0_val_4_addr_reg_2660;
reg   [10:0] k_buf_0_val_5_addr_reg_2666;
reg   [10:0] k_buf_1_val_3_addr_reg_2672;
reg   [10:0] k_buf_1_val_4_addr_reg_2678;
reg   [10:0] k_buf_1_val_5_addr_reg_2684;
reg   [10:0] k_buf_2_val_3_addr_reg_2690;
reg   [10:0] k_buf_2_val_4_addr_reg_2696;
reg   [10:0] k_buf_2_val_5_addr_reg_2702;
wire   [7:0] src_kernel_win_0_va_6_fu_1177_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_2708;
wire   [7:0] src_kernel_win_0_va_7_fu_1195_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_2715;
wire   [7:0] src_kernel_win_0_va_8_fu_1213_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_2722;
wire   [7:0] src_kernel_win_1_va_6_fu_1342_p3;
reg   [7:0] src_kernel_win_1_va_6_reg_2728;
wire   [7:0] src_kernel_win_1_va_7_fu_1360_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_2735;
wire   [7:0] src_kernel_win_1_va_8_fu_1378_p3;
reg   [7:0] src_kernel_win_1_va_8_reg_2742;
wire   [7:0] src_kernel_win_2_va_9_fu_1489_p3;
reg   [7:0] src_kernel_win_2_va_9_reg_2748;
wire   [7:0] src_kernel_win_2_va_10_fu_1507_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_2755;
wire   [7:0] src_kernel_win_2_va_11_fu_1525_p3;
reg   [7:0] src_kernel_win_2_va_11_reg_2762;
reg   [0:0] p_Result_s_reg_2768;
wire   [7:0] p_Val2_1_fu_1678_p2;
reg   [7:0] p_Val2_1_reg_2774;
reg   [2:0] tmp_37_reg_2779;
reg   [0:0] p_Result_1_reg_2784;
wire   [7:0] p_Val2_4_fu_1840_p2;
reg   [7:0] p_Val2_4_reg_2790;
reg   [2:0] tmp_49_reg_2795;
reg   [0:0] p_Result_2_reg_2800;
wire   [7:0] p_Val2_7_fu_2002_p2;
reg   [7:0] p_Val2_7_reg_2806;
reg   [2:0] tmp_59_reg_2811;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_condition_pp0_exit_iter2_state7;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [10:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [10:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [10:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
wire   [10:0] k_buf_1_val_3_address1;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
wire   [10:0] k_buf_1_val_4_address1;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
wire   [10:0] k_buf_1_val_5_address1;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
wire   [10:0] k_buf_2_val_3_address1;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
wire   [10:0] k_buf_2_val_4_address1;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
wire   [10:0] k_buf_2_val_5_address1;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_5_reg_508;
reg   [31:0] t_V_reg_519;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_26_fu_1030_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_154;
reg   [7:0] src_kernel_win_0_va_1_fu_158;
reg   [7:0] src_kernel_win_0_va_2_fu_162;
reg   [7:0] src_kernel_win_0_va_3_fu_166;
reg   [7:0] src_kernel_win_0_va_4_fu_170;
reg   [7:0] src_kernel_win_0_va_5_fu_174;
reg   [7:0] src_kernel_win_1_va_fu_178;
reg   [7:0] src_kernel_win_1_va_1_fu_182;
reg   [7:0] src_kernel_win_1_va_2_fu_186;
reg   [7:0] src_kernel_win_1_va_3_fu_190;
reg   [7:0] src_kernel_win_1_va_4_fu_194;
reg   [7:0] src_kernel_win_1_va_5_fu_198;
reg   [7:0] src_kernel_win_2_va_fu_202;
reg   [7:0] src_kernel_win_2_va_1_fu_206;
reg   [7:0] src_kernel_win_2_va_2_fu_210;
reg   [7:0] src_kernel_win_2_va_3_fu_214;
reg   [7:0] src_kernel_win_2_va_4_fu_218;
reg   [7:0] src_kernel_win_2_va_5_fu_222;
reg   [7:0] right_border_buf_0_s_fu_226;
wire   [7:0] col_buf_0_val_0_0_fu_1084_p3;
reg   [7:0] right_border_buf_0_1_fu_230;
reg   [7:0] right_border_buf_2_s_fu_234;
reg   [7:0] right_border_buf_0_2_fu_238;
wire   [7:0] col_buf_0_val_1_0_fu_1102_p3;
reg   [7:0] right_border_buf_0_3_fu_242;
reg   [7:0] right_border_buf_2_1_fu_246;
wire   [7:0] col_buf_2_val_2_0_fu_1441_p3;
reg   [7:0] right_border_buf_0_4_fu_250;
wire   [7:0] col_buf_0_val_2_0_fu_1120_p3;
reg   [7:0] right_border_buf_0_5_fu_254;
reg   [7:0] right_border_buf_2_2_fu_258;
reg   [7:0] right_border_buf_1_s_fu_262;
wire   [7:0] col_buf_1_val_0_0_fu_1249_p3;
reg   [7:0] right_border_buf_1_1_fu_266;
reg   [7:0] right_border_buf_2_3_fu_270;
wire   [7:0] col_buf_2_val_1_0_fu_1423_p3;
reg   [7:0] right_border_buf_1_2_fu_274;
wire   [7:0] col_buf_1_val_1_0_fu_1267_p3;
reg   [7:0] right_border_buf_1_3_fu_278;
reg   [7:0] right_border_buf_2_4_fu_282;
reg   [7:0] right_border_buf_1_4_fu_286;
wire   [7:0] col_buf_1_val_2_0_fu_1285_p3;
reg   [7:0] right_border_buf_1_5_fu_290;
reg   [7:0] right_border_buf_2_5_fu_294;
wire   [7:0] col_buf_2_val_0_0_fu_1405_p3;
wire   [31:0] tmp_fu_573_p2;
wire   [31:0] tmp_3_fu_584_p2;
wire   [30:0] tmp_10_fu_611_p4;
wire   [31:0] tmp_13_fu_644_p2;
wire   [0:0] tmp_14_fu_650_p3;
wire   [0:0] tmp_16_fu_664_p2;
wire   [0:0] rev_fu_658_p2;
wire   [0:0] tmp_17_fu_675_p3;
wire   [31:0] p_assign_7_fu_683_p2;
wire   [31:0] p_p2_i498_i_fu_689_p3;
wire   [31:0] p_assign_6_0_1_fu_707_p2;
wire   [0:0] tmp_20_fu_713_p3;
wire   [0:0] tmp_139_0_1_fu_727_p2;
wire   [0:0] rev1_fu_721_p2;
wire   [0:0] tmp_21_fu_738_p3;
wire   [31:0] p_assign_7_0_1_fu_746_p2;
wire   [31:0] p_p2_i498_i_0_1_fu_752_p3;
wire   [31:0] p_assign_6_0_2_fu_770_p2;
wire   [0:0] tmp_22_fu_776_p3;
wire   [0:0] tmp_139_0_2_fu_790_p2;
wire   [0:0] rev2_fu_784_p2;
wire   [0:0] tmp_23_fu_801_p3;
wire   [31:0] p_assign_7_0_2_fu_809_p2;
wire   [31:0] p_p2_i498_i_0_2_fu_815_p3;
wire   [0:0] tmp_19_fu_697_p2;
wire   [31:0] p_assign_8_fu_702_p2;
wire   [0:0] or_cond_i497_i_fu_669_p2;
wire   [31:0] p_p2_i498_i_0_p_assig_fu_833_p3;
wire   [0:0] tmp_148_0_1_fu_760_p2;
wire   [31:0] p_assign_8_0_1_fu_765_p2;
wire   [0:0] or_cond_i497_i_0_1_fu_732_p2;
wire   [31:0] p_p2_i498_i_0_1_p_ass_fu_849_p3;
wire   [0:0] tmp_148_0_2_fu_823_p2;
wire   [31:0] p_assign_8_0_2_fu_828_p2;
wire   [0:0] or_cond_i497_i_0_2_fu_795_p2;
wire   [31:0] p_p2_i498_i_0_2_p_ass_fu_865_p3;
wire   [31:0] row_assign_9_fu_886_p2;
wire   [31:0] row_assign_9_0_1_fu_894_p2;
wire   [31:0] row_assign_9_0_2_fu_902_p2;
wire   [30:0] tmp_35_fu_921_p4;
wire   [31:0] ImagLoc_x_fu_937_p2;
wire   [0:0] tmp_36_fu_943_p3;
wire   [0:0] tmp_18_fu_957_p2;
wire   [0:0] rev3_fu_951_p2;
wire   [0:0] tmp_38_fu_968_p3;
wire   [31:0] p_assign_1_fu_976_p2;
wire   [31:0] p_p2_i_i_fu_982_p3;
wire   [0:0] tmp_25_fu_990_p2;
wire   [31:0] p_assign_2_fu_995_p2;
wire   [31:0] p_p2_i_i_p_assign_2_fu_1000_p3;
wire   [0:0] icmp1_fu_931_p2;
wire   [31:0] col_assign_2_fu_1026_p2;
wire   [7:0] tmp_27_fu_1073_p5;
wire   [7:0] tmp_28_fu_1091_p5;
wire   [7:0] tmp_29_fu_1109_p5;
wire   [7:0] tmp_30_fu_1166_p5;
wire   [7:0] tmp_31_fu_1184_p5;
wire   [7:0] tmp_32_fu_1202_p5;
wire   [7:0] tmp_39_fu_1238_p5;
wire   [7:0] tmp_40_fu_1256_p5;
wire   [7:0] tmp_41_fu_1274_p5;
wire   [7:0] tmp_42_fu_1331_p5;
wire   [7:0] tmp_43_fu_1349_p5;
wire   [7:0] tmp_44_fu_1367_p5;
wire   [7:0] tmp_51_fu_1394_p5;
wire   [7:0] tmp_52_fu_1412_p5;
wire   [7:0] tmp_53_fu_1430_p5;
wire   [7:0] tmp_54_fu_1478_p5;
wire   [7:0] tmp_55_fu_1496_p5;
wire   [7:0] tmp_56_fu_1514_p5;
wire   [8:0] tmp_155_0_0_2_cast_fu_1545_p1;
wire   [8:0] r_V_0_0_cast_fu_1541_p1;
wire  signed [8:0] sum_V_0_0_2_fu_1548_p2;
wire   [8:0] p_shl_fu_1558_p3;
wire   [9:0] p_shl_cast_fu_1566_p1;
wire  signed [9:0] r_V_2_0_1_fu_1570_p2;
wire   [8:0] r_V_2_0_1_2_fu_1588_p3;
wire   [8:0] r_V_0_2_cast_fu_1604_p1;
wire  signed [8:0] r_V_2_0_2_fu_1608_p2;
wire  signed [10:0] tmp_155_0_2_cast_fu_1614_p1;
wire  signed [10:0] tmp_155_0_1_cast_fu_1576_p1;
wire   [9:0] tmp_155_0_2_2_cast_c_fu_1622_p1;
wire  signed [9:0] sum_V_0_0_2_cast_cas_fu_1554_p1;
wire   [9:0] tmp23_fu_1631_p2;
wire   [10:0] tmp_155_0_1_cast_57_fu_1595_p1;
wire  signed [10:0] tmp23_cast_fu_1637_p1;
wire   [10:0] tmp21_fu_1625_p2;
wire   [10:0] tmp22_fu_1641_p2;
wire   [10:0] p_Val2_s_fu_1647_p2;
wire   [7:0] tmp_50_fu_1584_p1;
wire   [7:0] tmp_48_fu_1580_p1;
wire   [7:0] tmp_58_fu_1618_p1;
wire   [7:0] tmp_57_fu_1599_p2;
wire   [7:0] tmp26_fu_1667_p2;
wire   [7:0] tmp24_fu_1661_p2;
wire   [7:0] tmp25_fu_1672_p2;
wire   [8:0] tmp_155_1_0_2_cast_fu_1707_p1;
wire   [8:0] r_V_1_0_cast_fu_1703_p1;
wire  signed [8:0] sum_V_1_0_2_fu_1710_p2;
wire   [8:0] p_shl1_fu_1720_p3;
wire   [9:0] p_shl1_cast_fu_1728_p1;
wire  signed [9:0] r_V_2_1_1_fu_1732_p2;
wire   [8:0] r_V_2_1_1_2_fu_1750_p3;
wire   [8:0] r_V_1_2_cast_fu_1766_p1;
wire  signed [8:0] r_V_2_1_2_fu_1770_p2;
wire  signed [10:0] tmp_155_1_2_cast_fu_1776_p1;
wire  signed [10:0] tmp_155_1_1_cast_fu_1738_p1;
wire   [9:0] tmp_155_1_2_2_cast_c_fu_1784_p1;
wire  signed [9:0] sum_V_1_0_2_cast_cas_fu_1716_p1;
wire   [9:0] tmp31_fu_1793_p2;
wire   [10:0] tmp_155_1_1_cast_58_fu_1757_p1;
wire  signed [10:0] tmp31_cast_fu_1799_p1;
wire   [10:0] tmp29_fu_1787_p2;
wire   [10:0] tmp30_fu_1803_p2;
wire   [10:0] p_Val2_3_fu_1809_p2;
wire   [7:0] tmp_65_fu_1746_p1;
wire   [7:0] tmp_64_fu_1742_p1;
wire   [7:0] tmp_67_fu_1780_p1;
wire   [7:0] tmp_66_fu_1761_p2;
wire   [7:0] tmp34_fu_1829_p2;
wire   [7:0] tmp32_fu_1823_p2;
wire   [7:0] tmp33_fu_1834_p2;
wire   [8:0] tmp_155_2_0_2_cast_fu_1869_p1;
wire   [8:0] r_V_213_0_cast_fu_1865_p1;
wire  signed [8:0] sum_V_2_0_2_fu_1872_p2;
wire   [8:0] p_shl2_fu_1882_p3;
wire   [9:0] p_shl2_cast_fu_1890_p1;
wire  signed [9:0] r_V_2_2_1_fu_1894_p2;
wire   [8:0] r_V_2_2_1_2_fu_1912_p3;
wire   [8:0] r_V_213_2_cast_fu_1928_p1;
wire  signed [8:0] r_V_2_2_2_fu_1932_p2;
wire  signed [10:0] tmp_155_2_2_cast_fu_1938_p1;
wire  signed [10:0] tmp_155_2_1_cast_fu_1900_p1;
wire   [9:0] tmp_155_2_2_2_cast_c_fu_1946_p1;
wire  signed [9:0] sum_V_2_0_2_cast_cas_fu_1878_p1;
wire   [9:0] tmp39_fu_1955_p2;
wire   [10:0] tmp_155_2_1_cast_59_fu_1919_p1;
wire  signed [10:0] tmp39_cast_fu_1961_p1;
wire   [10:0] tmp37_fu_1949_p2;
wire   [10:0] tmp38_fu_1965_p2;
wire   [10:0] p_Val2_6_fu_1971_p2;
wire   [7:0] tmp_73_fu_1908_p1;
wire   [7:0] tmp_72_fu_1904_p1;
wire   [7:0] tmp_75_fu_1942_p1;
wire   [7:0] tmp_74_fu_1923_p2;
wire   [7:0] tmp42_fu_1991_p2;
wire   [7:0] tmp40_fu_1985_p2;
wire   [7:0] tmp41_fu_1996_p2;
wire   [0:0] not_i_i_fu_2131_p2;
wire   [0:0] tmp_i_i_fu_2126_p2;
wire   [0:0] overflow_fu_2136_p2;
wire   [0:0] tmp_1_i_i_fu_2150_p2;
wire   [7:0] p_mux_i_i_cast_fu_2142_p3;
wire   [0:0] not_i_i1_fu_2168_p2;
wire   [0:0] tmp_i_i1_fu_2163_p2;
wire   [0:0] overflow_1_fu_2173_p2;
wire   [0:0] tmp_1_i_i1_fu_2187_p2;
wire   [7:0] p_mux_i_i30_cast_fu_2179_p3;
wire   [0:0] not_i_i2_fu_2205_p2;
wire   [0:0] tmp_i_i2_fu_2200_p2;
wire   [0:0] overflow_2_fu_2210_p2;
wire   [0:0] tmp_1_i_i2_fu_2224_p2;
wire   [7:0] p_mux_i_i39_cast_fu_2216_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_186;
reg    ap_enable_state6_pp0_iter1_stage0;
reg    ap_enable_operation_217;
reg    ap_enable_state7_pp0_iter2_stage0;
reg    ap_predicate_op231_store_state7;
reg    ap_enable_operation_231;
reg    ap_predicate_op239_store_state7;
reg    ap_enable_operation_239;
reg    ap_enable_operation_189;
reg    ap_enable_operation_220;
reg    ap_predicate_op229_store_state7;
reg    ap_enable_operation_229;
reg    ap_predicate_op237_store_state7;
reg    ap_enable_operation_237;
reg    ap_predicate_op191_load_state6;
reg    ap_enable_operation_191;
reg    ap_predicate_op223_load_state7;
reg    ap_enable_operation_223;
reg    ap_predicate_op227_store_state7;
reg    ap_enable_operation_227;
reg    ap_predicate_op236_store_state7;
reg    ap_enable_operation_236;
reg    ap_enable_operation_193;
reg    ap_enable_operation_259;
reg    ap_predicate_op273_store_state7;
reg    ap_enable_operation_273;
reg    ap_predicate_op281_store_state7;
reg    ap_enable_operation_281;
reg    ap_enable_operation_195;
reg    ap_enable_operation_262;
reg    ap_predicate_op271_store_state7;
reg    ap_enable_operation_271;
reg    ap_predicate_op279_store_state7;
reg    ap_enable_operation_279;
reg    ap_predicate_op197_load_state6;
reg    ap_enable_operation_197;
reg    ap_predicate_op265_load_state7;
reg    ap_enable_operation_265;
reg    ap_predicate_op269_store_state7;
reg    ap_enable_operation_269;
reg    ap_predicate_op278_store_state7;
reg    ap_enable_operation_278;
reg    ap_enable_operation_199;
reg    ap_enable_operation_298;
reg    ap_predicate_op312_store_state7;
reg    ap_enable_operation_312;
reg    ap_predicate_op317_store_state7;
reg    ap_enable_operation_317;
reg    ap_enable_operation_201;
reg    ap_enable_operation_301;
reg    ap_predicate_op310_store_state7;
reg    ap_enable_operation_310;
reg    ap_predicate_op315_store_state7;
reg    ap_enable_operation_315;
reg    ap_predicate_op203_load_state6;
reg    ap_enable_operation_203;
reg    ap_predicate_op304_load_state7;
reg    ap_enable_operation_304;
reg    ap_predicate_op308_store_state7;
reg    ap_enable_operation_308;
reg    ap_predicate_op314_store_state7;
reg    ap_enable_operation_314;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1657;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_address1),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_address1),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_address1),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_address1),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_address1),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_address1),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U21(
    .din0(right_border_buf_0_s_fu_226),
    .din1(right_border_buf_0_1_fu_230),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_27_fu_1073_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U22(
    .din0(right_border_buf_0_2_fu_238),
    .din1(right_border_buf_0_3_fu_242),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_28_fu_1091_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U23(
    .din0(right_border_buf_0_4_fu_250),
    .din1(right_border_buf_0_5_fu_254),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_29_fu_1109_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U24(
    .din0(col_buf_0_val_0_0_fu_1084_p3),
    .din1(col_buf_0_val_1_0_fu_1102_p3),
    .din2(col_buf_0_val_2_0_fu_1120_p3),
    .din3(tmp_24_reg_2584),
    .dout(tmp_30_fu_1166_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U25(
    .din0(col_buf_0_val_0_0_fu_1084_p3),
    .din1(col_buf_0_val_1_0_fu_1102_p3),
    .din2(col_buf_0_val_2_0_fu_1120_p3),
    .din3(tmp_33_reg_2591),
    .dout(tmp_31_fu_1184_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U26(
    .din0(col_buf_0_val_0_0_fu_1084_p3),
    .din1(col_buf_0_val_1_0_fu_1102_p3),
    .din2(col_buf_0_val_2_0_fu_1120_p3),
    .din3(tmp_34_reg_2598),
    .dout(tmp_32_fu_1202_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U27(
    .din0(right_border_buf_1_s_fu_262),
    .din1(right_border_buf_1_1_fu_266),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_39_fu_1238_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U28(
    .din0(right_border_buf_1_2_fu_274),
    .din1(right_border_buf_1_3_fu_278),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_40_fu_1256_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U29(
    .din0(right_border_buf_1_4_fu_286),
    .din1(right_border_buf_1_5_fu_290),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_41_fu_1274_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U30(
    .din0(col_buf_1_val_0_0_fu_1249_p3),
    .din1(col_buf_1_val_1_0_fu_1267_p3),
    .din2(col_buf_1_val_2_0_fu_1285_p3),
    .din3(tmp_24_reg_2584),
    .dout(tmp_42_fu_1331_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U31(
    .din0(col_buf_1_val_0_0_fu_1249_p3),
    .din1(col_buf_1_val_1_0_fu_1267_p3),
    .din2(col_buf_1_val_2_0_fu_1285_p3),
    .din3(tmp_33_reg_2591),
    .dout(tmp_43_fu_1349_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U32(
    .din0(col_buf_1_val_0_0_fu_1249_p3),
    .din1(col_buf_1_val_1_0_fu_1267_p3),
    .din2(col_buf_1_val_2_0_fu_1285_p3),
    .din3(tmp_34_reg_2598),
    .dout(tmp_44_fu_1367_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U33(
    .din0(right_border_buf_2_5_fu_294),
    .din1(right_border_buf_2_4_fu_282),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_51_fu_1394_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U34(
    .din0(right_border_buf_2_3_fu_270),
    .din1(right_border_buf_2_2_fu_258),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_52_fu_1412_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U35(
    .din0(right_border_buf_2_1_fu_246),
    .din1(right_border_buf_2_s_fu_234),
    .din2(8'd0),
    .din3(tmp_45_reg_2647),
    .dout(tmp_53_fu_1430_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U36(
    .din0(col_buf_2_val_0_0_fu_1405_p3),
    .din1(col_buf_2_val_1_0_fu_1423_p3),
    .din2(col_buf_2_val_2_0_fu_1441_p3),
    .din3(tmp_24_reg_2584),
    .dout(tmp_54_fu_1478_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U37(
    .din0(col_buf_2_val_0_0_fu_1405_p3),
    .din1(col_buf_2_val_1_0_fu_1423_p3),
    .din2(col_buf_2_val_2_0_fu_1441_p3),
    .din3(tmp_33_reg_2591),
    .dout(tmp_55_fu_1496_p5)
);

hls_sobel_mux_32_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
hls_sobel_mux_32_kbM_U38(
    .din0(col_buf_2_val_0_0_fu_1405_p3),
    .din1(col_buf_2_val_1_0_fu_1423_p3),
    .din2(col_buf_2_val_2_0_fu_1441_p3),
    .din3(tmp_34_reg_2598),
    .dout(tmp_56_fu_1514_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond461_i_fu_910_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state7)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_910_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_2_reg_530 <= j_V_fu_915_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_V_2_reg_530 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_V_reg_519 <= i_V_reg_2528;
    end else if (((tmp_7_fu_547_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_519 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_5_reg_508 <= 2'd0;
    end else if (((tmp_7_fu_547_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_5_reg_508 <= tmp_6_fu_541_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_910_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_2624 <= brmerge_fu_1016_p2;
        or_cond_i_i_reg_2614 <= or_cond_i_i_fu_962_p2;
        or_cond_i_reg_2637 <= or_cond_i_fu_1021_p2;
        x_reg_2618 <= x_fu_1008_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_2624_pp0_iter1_reg <= brmerge_reg_2624;
        exitcond461_i_reg_2605 <= exitcond461_i_fu_910_p2;
        exitcond461_i_reg_2605_pp0_iter1_reg <= exitcond461_i_reg_2605;
        or_cond_i_i_reg_2614_pp0_iter1_reg <= or_cond_i_i_reg_2614;
        or_cond_i_reg_2637_pp0_iter1_reg <= or_cond_i_reg_2637;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond461_i_reg_2605_pp0_iter2_reg <= exitcond461_i_reg_2605_pp0_iter1_reg;
        or_cond_i_reg_2637_pp0_iter2_reg <= or_cond_i_reg_2637_pp0_iter1_reg;
        or_cond_i_reg_2637_pp0_iter3_reg <= or_cond_i_reg_2637_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2528 <= i_V_fu_600_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond462_i_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2538 <= icmp_fu_621_p2;
        tmp_113_0_1_reg_2547 <= tmp_113_0_1_fu_633_p2;
        tmp_11_reg_2543 <= tmp_11_fu_627_p2;
        tmp_12_reg_2551 <= tmp_12_fu_639_p2;
        tmp_4_reg_2533 <= tmp_4_fu_606_p2;
        y_0_1_reg_2569 <= y_0_1_fu_857_p3;
        y_0_2_reg_2574 <= y_0_2_fu_873_p3;
        y_reg_2564 <= y_fu_841_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2605 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_addr_reg_2641 <= tmp_26_fu_1030_p1;
        k_buf_0_val_4_addr_reg_2660 <= tmp_26_fu_1030_p1;
        k_buf_0_val_5_addr_reg_2666 <= tmp_26_fu_1030_p1;
        k_buf_1_val_3_addr_reg_2672 <= tmp_26_fu_1030_p1;
        k_buf_1_val_4_addr_reg_2678 <= tmp_26_fu_1030_p1;
        k_buf_1_val_5_addr_reg_2684 <= tmp_26_fu_1030_p1;
        k_buf_2_val_3_addr_reg_2690 <= tmp_26_fu_1030_p1;
        k_buf_2_val_4_addr_reg_2696 <= tmp_26_fu_1030_p1;
        k_buf_2_val_5_addr_reg_2702 <= tmp_26_fu_1030_p1;
        tmp_45_reg_2647 <= tmp_45_fu_1042_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2637_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Result_1_reg_2784 <= p_Val2_3_fu_1809_p2[32'd10];
        p_Result_2_reg_2800 <= p_Val2_6_fu_1971_p2[32'd10];
        p_Result_s_reg_2768 <= p_Val2_s_fu_1647_p2[32'd10];
        p_Val2_1_reg_2774 <= p_Val2_1_fu_1678_p2;
        p_Val2_4_reg_2790 <= p_Val2_4_fu_1840_p2;
        p_Val2_7_reg_2806 <= p_Val2_7_fu_2002_p2;
        tmp_37_reg_2779 <= {{p_Val2_s_fu_1647_p2[10:8]}};
        tmp_49_reg_2795 <= {{p_Val2_3_fu_1809_p2[10:8]}};
        tmp_59_reg_2811 <= {{p_Val2_6_fu_1971_p2[10:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_547_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_neg466_i_reg_2501 <= p_neg466_i_fu_563_p2;
        tmp_1_reg_2496 <= tmp_1_fu_558_p2;
        tmp_65_2_reg_2520[31 : 1] <= tmp_65_2_fu_589_p2[31 : 1];
        tmp_8_reg_2508 <= tmp_8_fu_568_p2;
        tmp_9_reg_2513[31 : 1] <= tmp_9_fu_578_p2[31 : 1];
        tmp_s_reg_2491 <= tmp_s_fu_553_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        right_border_buf_0_1_fu_230 <= right_border_buf_0_s_fu_226;
        right_border_buf_0_2_fu_238 <= col_buf_0_val_1_0_fu_1102_p3;
        right_border_buf_0_3_fu_242 <= right_border_buf_0_2_fu_238;
        right_border_buf_0_4_fu_250 <= col_buf_0_val_2_0_fu_1120_p3;
        right_border_buf_0_5_fu_254 <= right_border_buf_0_4_fu_250;
        right_border_buf_0_s_fu_226 <= col_buf_0_val_0_0_fu_1084_p3;
        right_border_buf_1_1_fu_266 <= right_border_buf_1_s_fu_262;
        right_border_buf_1_2_fu_274 <= col_buf_1_val_1_0_fu_1267_p3;
        right_border_buf_1_3_fu_278 <= right_border_buf_1_2_fu_274;
        right_border_buf_1_4_fu_286 <= col_buf_1_val_2_0_fu_1285_p3;
        right_border_buf_1_5_fu_290 <= right_border_buf_1_4_fu_286;
        right_border_buf_1_s_fu_262 <= col_buf_1_val_0_0_fu_1249_p3;
        right_border_buf_2_1_fu_246 <= col_buf_2_val_2_0_fu_1441_p3;
        right_border_buf_2_2_fu_258 <= right_border_buf_2_3_fu_270;
        right_border_buf_2_3_fu_270 <= col_buf_2_val_1_0_fu_1423_p3;
        right_border_buf_2_4_fu_282 <= right_border_buf_2_5_fu_294;
        right_border_buf_2_5_fu_294 <= col_buf_2_val_0_0_fu_1405_p3;
        right_border_buf_2_s_fu_234 <= right_border_buf_2_1_fu_246;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2605_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        src_kernel_win_0_va_1_fu_158 <= src_kernel_win_0_va_fu_154;
        src_kernel_win_0_va_2_fu_162 <= src_kernel_win_0_va_7_reg_2715;
        src_kernel_win_0_va_3_fu_166 <= src_kernel_win_0_va_2_fu_162;
        src_kernel_win_0_va_4_fu_170 <= src_kernel_win_0_va_8_reg_2722;
        src_kernel_win_0_va_5_fu_174 <= src_kernel_win_0_va_4_fu_170;
        src_kernel_win_0_va_fu_154 <= src_kernel_win_0_va_6_reg_2708;
        src_kernel_win_1_va_1_fu_182 <= src_kernel_win_1_va_fu_178;
        src_kernel_win_1_va_2_fu_186 <= src_kernel_win_1_va_7_reg_2735;
        src_kernel_win_1_va_3_fu_190 <= src_kernel_win_1_va_2_fu_186;
        src_kernel_win_1_va_4_fu_194 <= src_kernel_win_1_va_8_reg_2742;
        src_kernel_win_1_va_5_fu_198 <= src_kernel_win_1_va_4_fu_194;
        src_kernel_win_1_va_fu_178 <= src_kernel_win_1_va_6_reg_2728;
        src_kernel_win_2_va_1_fu_206 <= src_kernel_win_2_va_fu_202;
        src_kernel_win_2_va_2_fu_210 <= src_kernel_win_2_va_10_reg_2755;
        src_kernel_win_2_va_3_fu_214 <= src_kernel_win_2_va_2_fu_210;
        src_kernel_win_2_va_4_fu_218 <= src_kernel_win_2_va_11_reg_2762;
        src_kernel_win_2_va_5_fu_222 <= src_kernel_win_2_va_4_fu_218;
        src_kernel_win_2_va_fu_202 <= src_kernel_win_2_va_9_reg_2748;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_6_reg_2708 <= src_kernel_win_0_va_6_fu_1177_p3;
        src_kernel_win_0_va_7_reg_2715 <= src_kernel_win_0_va_7_fu_1195_p3;
        src_kernel_win_0_va_8_reg_2722 <= src_kernel_win_0_va_8_fu_1213_p3;
        src_kernel_win_1_va_6_reg_2728 <= src_kernel_win_1_va_6_fu_1342_p3;
        src_kernel_win_1_va_7_reg_2735 <= src_kernel_win_1_va_7_fu_1360_p3;
        src_kernel_win_1_va_8_reg_2742 <= src_kernel_win_1_va_8_fu_1378_p3;
        src_kernel_win_2_va_10_reg_2755 <= src_kernel_win_2_va_10_fu_1507_p3;
        src_kernel_win_2_va_11_reg_2762 <= src_kernel_win_2_va_11_fu_1525_p3;
        src_kernel_win_2_va_9_reg_2748 <= src_kernel_win_2_va_9_fu_1489_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_24_reg_2584 <= tmp_24_fu_890_p1;
        tmp_33_reg_2591 <= tmp_33_fu_898_p1;
        tmp_34_reg_2598 <= tmp_34_fu_906_p1;
        tmp_69_0_0_not_reg_2579 <= tmp_69_0_0_not_fu_881_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond462_i_fu_595_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond462_i_fu_595_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1657)) begin
        if (((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_113_0_1_reg_2547 == 1'd1) & (icmp_reg_2538 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1657)) begin
        if (((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_11_reg_2543 == 1'd1) & (icmp_reg_2538 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1657)) begin
        if (((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1))) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (((tmp_113_0_1_reg_2547 == 1'd1) & (icmp_reg_2538 == 1'd0))) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1657)) begin
        if (((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1))) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (((tmp_11_reg_2543 == 1'd1) & (icmp_reg_2538 == 1'd0))) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1657)) begin
        if (((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1))) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (((tmp_113_0_1_reg_2547 == 1'd1) & (icmp_reg_2538 == 1'd0))) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1657)) begin
        if (((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1))) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (((tmp_11_reg_2543 == 1'd1) & (icmp_reg_2538 == 1'd0))) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op238_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op226_read_state7 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op280_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op268_read_state7 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op316_read_state7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op307_read_state7 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_7_fu_547_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond462_i_fu_595_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_937_p2 = ($signed(32'd4294967295) + $signed(t_V_2_reg_530));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op307_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op280_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op268_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op238_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op226_read_state7 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op307_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op280_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op268_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op238_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op226_read_state7 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op307_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op280_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op268_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op238_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op226_read_state7 == 1'b1)))));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter2 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op316_read_state7 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op307_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op280_read_state7 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op268_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op238_read_state7 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op226_read_state7 == 1'b1)));
end

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter4 = (((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2637_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1657 = ((or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_operation_186 = (exitcond461_i_reg_2605 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_189 = (exitcond461_i_reg_2605 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_191 = (ap_predicate_op191_load_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_193 = (exitcond461_i_reg_2605 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_195 = (exitcond461_i_reg_2605 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_197 = (ap_predicate_op197_load_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_199 = (exitcond461_i_reg_2605 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_201 = (exitcond461_i_reg_2605 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_203 = (ap_predicate_op203_load_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_217 = (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_220 = (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_223 = (ap_predicate_op223_load_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_227 = (ap_predicate_op227_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_229 = (ap_predicate_op229_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_231 = (ap_predicate_op231_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_236 = (ap_predicate_op236_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_237 = (ap_predicate_op237_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_239 = (ap_predicate_op239_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_259 = (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_262 = (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_265 = (ap_predicate_op265_load_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_269 = (ap_predicate_op269_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_271 = (ap_predicate_op271_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_273 = (ap_predicate_op273_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_278 = (ap_predicate_op278_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_279 = (ap_predicate_op279_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_281 = (ap_predicate_op281_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_298 = (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_301 = (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_304 = (ap_predicate_op304_load_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_308 = (ap_predicate_op308_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_310 = (ap_predicate_op310_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_312 = (ap_predicate_op312_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_314 = (ap_predicate_op314_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_315 = (ap_predicate_op315_store_state7 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_317 = (ap_predicate_op317_store_state7 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state6_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state7_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op191_load_state6 = ((brmerge_reg_2624 == 1'd1) & (exitcond461_i_reg_2605 == 1'd0));
end

always @ (*) begin
    ap_predicate_op197_load_state6 = ((brmerge_reg_2624 == 1'd1) & (exitcond461_i_reg_2605 == 1'd0));
end

always @ (*) begin
    ap_predicate_op203_load_state6 = ((brmerge_reg_2624 == 1'd1) & (exitcond461_i_reg_2605 == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_load_state7 = ((brmerge_reg_2624_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op226_read_state7 = ((or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op227_store_state7 = ((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op229_store_state7 = ((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op231_store_state7 = ((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op236_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op237_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op238_read_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op239_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op265_load_state7 = ((brmerge_reg_2624_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op268_read_state7 = ((or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op269_store_state7 = ((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op271_store_state7 = ((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op273_store_state7 = ((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op278_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op279_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op280_read_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op281_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op304_load_state7 = ((brmerge_reg_2624_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op307_read_state7 = ((or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op308_store_state7 = ((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op310_store_state7 = ((tmp_113_0_1_reg_2547 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op312_store_state7 = ((tmp_11_reg_2543 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (icmp_reg_2538 == 1'd0) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op314_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op315_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op316_read_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op317_store_state7 = ((tmp_4_reg_2533 == 1'd1) & (icmp_reg_2538 == 1'd1) & (or_cond_i_i_reg_2614_pp0_iter1_reg == 1'd1) & (exitcond461_i_reg_2605_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_1016_p2 = (tmp_69_0_0_not_reg_2579 | tmp_18_fu_957_p2);

assign col_assign_2_fu_1026_p2 = (tmp_8_reg_2508 - x_reg_2618);

assign col_buf_0_val_0_0_fu_1084_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_27_fu_1073_p5);

assign col_buf_0_val_1_0_fu_1102_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_28_fu_1091_p5);

assign col_buf_0_val_2_0_fu_1120_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_29_fu_1109_p5);

assign col_buf_1_val_0_0_fu_1249_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_39_fu_1238_p5);

assign col_buf_1_val_1_0_fu_1267_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_40_fu_1256_p5);

assign col_buf_1_val_2_0_fu_1285_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_41_fu_1274_p5);

assign col_buf_2_val_0_0_fu_1405_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_51_fu_1394_p5);

assign col_buf_2_val_1_0_fu_1423_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_52_fu_1412_p5);

assign col_buf_2_val_2_0_fu_1441_p3 = ((brmerge_reg_2624_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_53_fu_1430_p5);

assign exitcond461_i_fu_910_p2 = ((t_V_2_reg_530 == tmp_s_reg_2491) ? 1'b1 : 1'b0);

assign exitcond462_i_fu_595_p2 = ((t_V_reg_519 == tmp_1_reg_2496) ? 1'b1 : 1'b0);

assign i_V_fu_600_p2 = (t_V_reg_519 + 32'd1);

assign icmp1_fu_931_p2 = ((tmp_35_fu_921_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_fu_621_p2 = ((tmp_10_fu_611_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_915_p2 = (t_V_2_reg_530 + 32'd1);

assign k_buf_0_val_3_address0 = tmp_26_fu_1030_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_2641;

assign k_buf_0_val_4_address0 = tmp_26_fu_1030_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_2660;

assign k_buf_0_val_5_address0 = tmp_26_fu_1030_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_2666;

assign k_buf_1_val_3_address0 = tmp_26_fu_1030_p1;

assign k_buf_1_val_3_address1 = k_buf_1_val_3_addr_reg_2672;

assign k_buf_1_val_4_address0 = tmp_26_fu_1030_p1;

assign k_buf_1_val_4_address1 = k_buf_1_val_4_addr_reg_2678;

assign k_buf_1_val_5_address0 = tmp_26_fu_1030_p1;

assign k_buf_1_val_5_address1 = k_buf_1_val_5_addr_reg_2684;

assign k_buf_2_val_3_address0 = tmp_26_fu_1030_p1;

assign k_buf_2_val_3_address1 = k_buf_2_val_3_addr_reg_2690;

assign k_buf_2_val_4_address0 = tmp_26_fu_1030_p1;

assign k_buf_2_val_4_address1 = k_buf_2_val_4_addr_reg_2696;

assign k_buf_2_val_5_address0 = tmp_26_fu_1030_p1;

assign k_buf_2_val_5_address1 = k_buf_2_val_5_addr_reg_2702;

assign not_i_i1_fu_2168_p2 = ((tmp_49_reg_2795 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i2_fu_2205_p2 = ((tmp_59_reg_2811 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_fu_2131_p2 = ((tmp_37_reg_2779 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i497_i_0_1_fu_732_p2 = (tmp_139_0_1_fu_727_p2 & rev1_fu_721_p2);

assign or_cond_i497_i_0_2_fu_795_p2 = (tmp_139_0_2_fu_790_p2 & rev2_fu_784_p2);

assign or_cond_i497_i_fu_669_p2 = (tmp_16_fu_664_p2 & rev_fu_658_p2);

assign or_cond_i_fu_1021_p2 = (icmp_reg_2538 & icmp1_fu_931_p2);

assign or_cond_i_i_fu_962_p2 = (tmp_18_fu_957_p2 & rev3_fu_951_p2);

assign overflow_1_fu_2173_p2 = (tmp_i_i1_fu_2163_p2 & not_i_i1_fu_2168_p2);

assign overflow_2_fu_2210_p2 = (tmp_i_i2_fu_2200_p2 & not_i_i2_fu_2205_p2);

assign overflow_fu_2136_p2 = (tmp_i_i_fu_2126_p2 & not_i_i_fu_2131_p2);

assign p_Val2_1_fu_1678_p2 = (tmp24_fu_1661_p2 + tmp25_fu_1672_p2);

assign p_Val2_3_fu_1809_p2 = (tmp29_fu_1787_p2 + tmp30_fu_1803_p2);

assign p_Val2_4_fu_1840_p2 = (tmp32_fu_1823_p2 + tmp33_fu_1834_p2);

assign p_Val2_6_fu_1971_p2 = (tmp37_fu_1949_p2 + tmp38_fu_1965_p2);

assign p_Val2_7_fu_2002_p2 = (tmp40_fu_1985_p2 + tmp41_fu_1996_p2);

assign p_Val2_s_fu_1647_p2 = (tmp21_fu_1625_p2 + tmp22_fu_1641_p2);

assign p_assign_1_fu_976_p2 = (32'd1 - t_V_2_reg_530);

assign p_assign_2_fu_995_p2 = (tmp_65_2_reg_2520 - p_p2_i_i_fu_982_p3);

assign p_assign_6_0_1_fu_707_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_519));

assign p_assign_6_0_2_fu_770_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_519));

assign p_assign_7_0_1_fu_746_p2 = (32'd2 - t_V_reg_519);

assign p_assign_7_0_2_fu_809_p2 = (32'd3 - t_V_reg_519);

assign p_assign_7_fu_683_p2 = (32'd1 - t_V_reg_519);

assign p_assign_8_0_1_fu_765_p2 = (tmp_9_reg_2513 - p_p2_i498_i_0_1_fu_752_p3);

assign p_assign_8_0_2_fu_828_p2 = (tmp_9_reg_2513 - p_p2_i498_i_0_2_fu_815_p3);

assign p_assign_8_fu_702_p2 = (tmp_9_reg_2513 - p_p2_i498_i_fu_689_p3);

assign p_dst_data_stream_0_V_din = ((tmp_1_i_i_fu_2150_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_2142_p3 : p_Val2_1_reg_2774);

assign p_dst_data_stream_1_V_din = ((tmp_1_i_i1_fu_2187_p2[0:0] === 1'b1) ? p_mux_i_i30_cast_fu_2179_p3 : p_Val2_4_reg_2790);

assign p_dst_data_stream_2_V_din = ((tmp_1_i_i2_fu_2224_p2[0:0] === 1'b1) ? p_mux_i_i39_cast_fu_2216_p3 : p_Val2_7_reg_2806);

assign p_mux_i_i30_cast_fu_2179_p3 = ((tmp_i_i1_fu_2163_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i39_cast_fu_2216_p3 = ((tmp_i_i2_fu_2200_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_2142_p3 = ((tmp_i_i_fu_2126_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_neg466_i_fu_563_p2 = ($signed(32'd4294967295) + $signed(p_src_rows_V_read));

assign p_p2_i498_i_0_1_fu_752_p3 = ((tmp_21_fu_738_p3[0:0] === 1'b1) ? p_assign_7_0_1_fu_746_p2 : p_assign_6_0_1_fu_707_p2);

assign p_p2_i498_i_0_1_p_ass_fu_849_p3 = ((tmp_148_0_1_fu_760_p2[0:0] === 1'b1) ? p_p2_i498_i_0_1_fu_752_p3 : p_assign_8_0_1_fu_765_p2);

assign p_p2_i498_i_0_2_fu_815_p3 = ((tmp_23_fu_801_p3[0:0] === 1'b1) ? p_assign_7_0_2_fu_809_p2 : p_assign_6_0_2_fu_770_p2);

assign p_p2_i498_i_0_2_p_ass_fu_865_p3 = ((tmp_148_0_2_fu_823_p2[0:0] === 1'b1) ? p_p2_i498_i_0_2_fu_815_p3 : p_assign_8_0_2_fu_828_p2);

assign p_p2_i498_i_0_p_assig_fu_833_p3 = ((tmp_19_fu_697_p2[0:0] === 1'b1) ? p_p2_i498_i_fu_689_p3 : p_assign_8_fu_702_p2);

assign p_p2_i498_i_fu_689_p3 = ((tmp_17_fu_675_p3[0:0] === 1'b1) ? p_assign_7_fu_683_p2 : tmp_13_fu_644_p2);

assign p_p2_i_i_fu_982_p3 = ((tmp_38_fu_968_p3[0:0] === 1'b1) ? p_assign_1_fu_976_p2 : ImagLoc_x_fu_937_p2);

assign p_p2_i_i_p_assign_2_fu_1000_p3 = ((tmp_25_fu_990_p2[0:0] === 1'b1) ? p_p2_i_i_fu_982_p3 : p_assign_2_fu_995_p2);

assign p_shl1_cast_fu_1728_p1 = p_shl1_fu_1720_p3;

assign p_shl1_fu_1720_p3 = {{src_kernel_win_1_va_3_fu_190}, {1'd0}};

assign p_shl2_cast_fu_1890_p1 = p_shl2_fu_1882_p3;

assign p_shl2_fu_1882_p3 = {{src_kernel_win_2_va_3_fu_214}, {1'd0}};

assign p_shl_cast_fu_1566_p1 = p_shl_fu_1558_p3;

assign p_shl_fu_1558_p3 = {{src_kernel_win_0_va_3_fu_166}, {1'd0}};

assign r_V_0_0_cast_fu_1541_p1 = src_kernel_win_0_va_5_fu_174;

assign r_V_0_2_cast_fu_1604_p1 = src_kernel_win_0_va_1_fu_158;

assign r_V_1_0_cast_fu_1703_p1 = src_kernel_win_1_va_5_fu_198;

assign r_V_1_2_cast_fu_1766_p1 = src_kernel_win_1_va_1_fu_182;

assign r_V_213_0_cast_fu_1865_p1 = src_kernel_win_2_va_5_fu_222;

assign r_V_213_2_cast_fu_1928_p1 = src_kernel_win_2_va_1_fu_206;

assign r_V_2_0_1_2_fu_1588_p3 = {{src_kernel_win_0_va_7_reg_2715}, {1'd0}};

assign r_V_2_0_1_fu_1570_p2 = (10'd0 - p_shl_cast_fu_1566_p1);

assign r_V_2_0_2_fu_1608_p2 = (9'd0 - r_V_0_2_cast_fu_1604_p1);

assign r_V_2_1_1_2_fu_1750_p3 = {{src_kernel_win_1_va_7_reg_2735}, {1'd0}};

assign r_V_2_1_1_fu_1732_p2 = (10'd0 - p_shl1_cast_fu_1728_p1);

assign r_V_2_1_2_fu_1770_p2 = (9'd0 - r_V_1_2_cast_fu_1766_p1);

assign r_V_2_2_1_2_fu_1912_p3 = {{src_kernel_win_2_va_10_reg_2755}, {1'd0}};

assign r_V_2_2_1_fu_1894_p2 = (10'd0 - p_shl2_cast_fu_1890_p1);

assign r_V_2_2_2_fu_1932_p2 = (9'd0 - r_V_213_2_cast_fu_1928_p1);

assign rev1_fu_721_p2 = (tmp_20_fu_713_p3 ^ 1'd1);

assign rev2_fu_784_p2 = (tmp_22_fu_776_p3 ^ 1'd1);

assign rev3_fu_951_p2 = (tmp_36_fu_943_p3 ^ 1'd1);

assign rev_fu_658_p2 = (tmp_14_fu_650_p3 ^ 1'd1);

assign row_assign_9_0_1_fu_894_p2 = (p_neg466_i_reg_2501 - y_0_1_reg_2569);

assign row_assign_9_0_2_fu_902_p2 = (p_neg466_i_reg_2501 - y_0_2_reg_2574);

assign row_assign_9_fu_886_p2 = (p_neg466_i_reg_2501 - y_reg_2564);

assign src_kernel_win_0_va_6_fu_1177_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_30_fu_1166_p5 : col_buf_0_val_0_0_fu_1084_p3);

assign src_kernel_win_0_va_7_fu_1195_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_31_fu_1184_p5 : col_buf_0_val_1_0_fu_1102_p3);

assign src_kernel_win_0_va_8_fu_1213_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_32_fu_1202_p5 : col_buf_0_val_2_0_fu_1120_p3);

assign src_kernel_win_1_va_6_fu_1342_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_42_fu_1331_p5 : col_buf_1_val_0_0_fu_1249_p3);

assign src_kernel_win_1_va_7_fu_1360_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_43_fu_1349_p5 : col_buf_1_val_1_0_fu_1267_p3);

assign src_kernel_win_1_va_8_fu_1378_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_44_fu_1367_p5 : col_buf_1_val_2_0_fu_1285_p3);

assign src_kernel_win_2_va_10_fu_1507_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_55_fu_1496_p5 : col_buf_2_val_1_0_fu_1423_p3);

assign src_kernel_win_2_va_11_fu_1525_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_56_fu_1514_p5 : col_buf_2_val_2_0_fu_1441_p3);

assign src_kernel_win_2_va_9_fu_1489_p3 = ((tmp_12_reg_2551[0:0] === 1'b1) ? tmp_54_fu_1478_p5 : col_buf_2_val_0_0_fu_1405_p3);

assign sum_V_0_0_2_cast_cas_fu_1554_p1 = sum_V_0_0_2_fu_1548_p2;

assign sum_V_0_0_2_fu_1548_p2 = (tmp_155_0_0_2_cast_fu_1545_p1 - r_V_0_0_cast_fu_1541_p1);

assign sum_V_1_0_2_cast_cas_fu_1716_p1 = sum_V_1_0_2_fu_1710_p2;

assign sum_V_1_0_2_fu_1710_p2 = (tmp_155_1_0_2_cast_fu_1707_p1 - r_V_1_0_cast_fu_1703_p1);

assign sum_V_2_0_2_cast_cas_fu_1878_p1 = sum_V_2_0_2_fu_1872_p2;

assign sum_V_2_0_2_fu_1872_p2 = (tmp_155_2_0_2_cast_fu_1869_p1 - r_V_213_0_cast_fu_1865_p1);

assign tmp21_fu_1625_p2 = ($signed(tmp_155_0_2_cast_fu_1614_p1) + $signed(tmp_155_0_1_cast_fu_1576_p1));

assign tmp22_fu_1641_p2 = ($signed(tmp_155_0_1_cast_57_fu_1595_p1) + $signed(tmp23_cast_fu_1637_p1));

assign tmp23_cast_fu_1637_p1 = $signed(tmp23_fu_1631_p2);

assign tmp23_fu_1631_p2 = ($signed(tmp_155_0_2_2_cast_c_fu_1622_p1) + $signed(sum_V_0_0_2_cast_cas_fu_1554_p1));

assign tmp24_fu_1661_p2 = (tmp_50_fu_1584_p1 + tmp_48_fu_1580_p1);

assign tmp25_fu_1672_p2 = (tmp_57_fu_1599_p2 + tmp26_fu_1667_p2);

assign tmp26_fu_1667_p2 = (src_kernel_win_0_va_6_reg_2708 + tmp_58_fu_1618_p1);

assign tmp29_fu_1787_p2 = ($signed(tmp_155_1_2_cast_fu_1776_p1) + $signed(tmp_155_1_1_cast_fu_1738_p1));

assign tmp30_fu_1803_p2 = ($signed(tmp_155_1_1_cast_58_fu_1757_p1) + $signed(tmp31_cast_fu_1799_p1));

assign tmp31_cast_fu_1799_p1 = $signed(tmp31_fu_1793_p2);

assign tmp31_fu_1793_p2 = ($signed(tmp_155_1_2_2_cast_c_fu_1784_p1) + $signed(sum_V_1_0_2_cast_cas_fu_1716_p1));

assign tmp32_fu_1823_p2 = (tmp_65_fu_1746_p1 + tmp_64_fu_1742_p1);

assign tmp33_fu_1834_p2 = (tmp_66_fu_1761_p2 + tmp34_fu_1829_p2);

assign tmp34_fu_1829_p2 = (src_kernel_win_1_va_6_reg_2728 + tmp_67_fu_1780_p1);

assign tmp37_fu_1949_p2 = ($signed(tmp_155_2_2_cast_fu_1938_p1) + $signed(tmp_155_2_1_cast_fu_1900_p1));

assign tmp38_fu_1965_p2 = ($signed(tmp_155_2_1_cast_59_fu_1919_p1) + $signed(tmp39_cast_fu_1961_p1));

assign tmp39_cast_fu_1961_p1 = $signed(tmp39_fu_1955_p2);

assign tmp39_fu_1955_p2 = ($signed(tmp_155_2_2_2_cast_c_fu_1946_p1) + $signed(sum_V_2_0_2_cast_cas_fu_1878_p1));

assign tmp40_fu_1985_p2 = (tmp_73_fu_1908_p1 + tmp_72_fu_1904_p1);

assign tmp41_fu_1996_p2 = (tmp_74_fu_1923_p2 + tmp42_fu_1991_p2);

assign tmp42_fu_1991_p2 = (src_kernel_win_2_va_9_reg_2748 + tmp_75_fu_1942_p1);

assign tmp_10_fu_611_p4 = {{t_V_reg_519[31:1]}};

assign tmp_113_0_1_fu_633_p2 = ((t_V_reg_519 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_627_p2 = ((t_V_reg_519 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_12_fu_639_p2 = ((t_V_reg_519 > p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_139_0_1_fu_727_p2 = (($signed(p_assign_6_0_1_fu_707_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_139_0_2_fu_790_p2 = (($signed(p_assign_6_0_2_fu_770_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_13_fu_644_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_519));

assign tmp_148_0_1_fu_760_p2 = (($signed(p_p2_i498_i_0_1_fu_752_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_148_0_2_fu_823_p2 = (($signed(p_p2_i498_i_0_2_fu_815_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_14_fu_650_p3 = tmp_13_fu_644_p2[32'd31];

assign tmp_155_0_0_2_cast_fu_1545_p1 = src_kernel_win_0_va_8_reg_2722;

assign tmp_155_0_1_cast_57_fu_1595_p1 = r_V_2_0_1_2_fu_1588_p3;

assign tmp_155_0_1_cast_fu_1576_p1 = r_V_2_0_1_fu_1570_p2;

assign tmp_155_0_2_2_cast_c_fu_1622_p1 = src_kernel_win_0_va_6_reg_2708;

assign tmp_155_0_2_cast_fu_1614_p1 = r_V_2_0_2_fu_1608_p2;

assign tmp_155_1_0_2_cast_fu_1707_p1 = src_kernel_win_1_va_8_reg_2742;

assign tmp_155_1_1_cast_58_fu_1757_p1 = r_V_2_1_1_2_fu_1750_p3;

assign tmp_155_1_1_cast_fu_1738_p1 = r_V_2_1_1_fu_1732_p2;

assign tmp_155_1_2_2_cast_c_fu_1784_p1 = src_kernel_win_1_va_6_reg_2728;

assign tmp_155_1_2_cast_fu_1776_p1 = r_V_2_1_2_fu_1770_p2;

assign tmp_155_2_0_2_cast_fu_1869_p1 = src_kernel_win_2_va_11_reg_2762;

assign tmp_155_2_1_cast_59_fu_1919_p1 = r_V_2_2_1_2_fu_1912_p3;

assign tmp_155_2_1_cast_fu_1900_p1 = r_V_2_2_1_fu_1894_p2;

assign tmp_155_2_2_2_cast_c_fu_1946_p1 = src_kernel_win_2_va_9_reg_2748;

assign tmp_155_2_2_cast_fu_1938_p1 = r_V_2_2_2_fu_1932_p2;

assign tmp_16_fu_664_p2 = (($signed(tmp_13_fu_644_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_17_fu_675_p3 = tmp_13_fu_644_p2[32'd31];

assign tmp_18_fu_957_p2 = (($signed(ImagLoc_x_fu_937_p2) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_19_fu_697_p2 = (($signed(p_p2_i498_i_fu_689_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_1_fu_558_p2 = (32'd2 + p_src_rows_V_read);

assign tmp_1_i_i1_fu_2187_p2 = (p_Result_1_reg_2784 | overflow_1_fu_2173_p2);

assign tmp_1_i_i2_fu_2224_p2 = (p_Result_2_reg_2800 | overflow_2_fu_2210_p2);

assign tmp_1_i_i_fu_2150_p2 = (p_Result_s_reg_2768 | overflow_fu_2136_p2);

assign tmp_20_fu_713_p3 = p_assign_6_0_1_fu_707_p2[32'd31];

assign tmp_21_fu_738_p3 = p_assign_6_0_1_fu_707_p2[32'd31];

assign tmp_22_fu_776_p3 = p_assign_6_0_2_fu_770_p2[32'd31];

assign tmp_23_fu_801_p3 = p_assign_6_0_2_fu_770_p2[32'd31];

assign tmp_24_fu_890_p1 = row_assign_9_fu_886_p2[1:0];

assign tmp_25_fu_990_p2 = (($signed(p_p2_i_i_fu_982_p3) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_26_fu_1030_p1 = x_reg_2618;

assign tmp_33_fu_898_p1 = row_assign_9_0_1_fu_894_p2[1:0];

assign tmp_34_fu_906_p1 = row_assign_9_0_2_fu_902_p2[1:0];

assign tmp_35_fu_921_p4 = {{t_V_2_reg_530[31:1]}};

assign tmp_36_fu_943_p3 = ImagLoc_x_fu_937_p2[32'd31];

assign tmp_38_fu_968_p3 = ImagLoc_x_fu_937_p2[32'd31];

assign tmp_3_fu_584_p2 = p_src_cols_V_read << 32'd1;

assign tmp_45_fu_1042_p1 = col_assign_2_fu_1026_p2[1:0];

assign tmp_48_fu_1580_p1 = sum_V_0_0_2_fu_1548_p2[7:0];

assign tmp_4_fu_606_p2 = ((t_V_reg_519 < p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_50_fu_1584_p1 = r_V_2_0_1_fu_1570_p2[7:0];

assign tmp_57_fu_1599_p2 = src_kernel_win_0_va_7_reg_2715 << 8'd1;

assign tmp_58_fu_1618_p1 = r_V_2_0_2_fu_1608_p2[7:0];

assign tmp_64_fu_1742_p1 = sum_V_1_0_2_fu_1710_p2[7:0];

assign tmp_65_2_fu_589_p2 = ($signed(32'd4294967294) + $signed(tmp_3_fu_584_p2));

assign tmp_65_fu_1746_p1 = r_V_2_1_1_fu_1732_p2[7:0];

assign tmp_66_fu_1761_p2 = src_kernel_win_1_va_7_reg_2735 << 8'd1;

assign tmp_67_fu_1780_p1 = r_V_2_1_2_fu_1770_p2[7:0];

assign tmp_69_0_0_not_fu_881_p2 = (tmp_4_reg_2533 ^ 1'd1);

assign tmp_6_fu_541_p2 = (tmp_5_reg_508 + 2'd1);

assign tmp_72_fu_1904_p1 = sum_V_2_0_2_fu_1872_p2[7:0];

assign tmp_73_fu_1908_p1 = r_V_2_2_1_fu_1894_p2[7:0];

assign tmp_74_fu_1923_p2 = src_kernel_win_2_va_10_reg_2755 << 8'd1;

assign tmp_75_fu_1942_p1 = r_V_2_2_2_fu_1932_p2[7:0];

assign tmp_7_fu_547_p2 = ((tmp_5_reg_508 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_8_fu_568_p2 = (32'd3 + p_src_cols_V_read);

assign tmp_9_fu_578_p2 = (32'd2 + tmp_fu_573_p2);

assign tmp_fu_573_p2 = p_src_rows_V_read << 32'd1;

assign tmp_i_i1_fu_2163_p2 = (p_Result_1_reg_2784 ^ 1'd1);

assign tmp_i_i2_fu_2200_p2 = (p_Result_2_reg_2800 ^ 1'd1);

assign tmp_i_i_fu_2126_p2 = (p_Result_s_reg_2768 ^ 1'd1);

assign tmp_s_fu_553_p2 = (32'd2 + p_src_cols_V_read);

assign x_fu_1008_p3 = ((or_cond_i_i_fu_962_p2[0:0] === 1'b1) ? ImagLoc_x_fu_937_p2 : p_p2_i_i_p_assign_2_fu_1000_p3);

assign y_0_1_fu_857_p3 = ((or_cond_i497_i_0_1_fu_732_p2[0:0] === 1'b1) ? p_assign_6_0_1_fu_707_p2 : p_p2_i498_i_0_1_p_ass_fu_849_p3);

assign y_0_2_fu_873_p3 = ((or_cond_i497_i_0_2_fu_795_p2[0:0] === 1'b1) ? p_assign_6_0_2_fu_770_p2 : p_p2_i498_i_0_2_p_ass_fu_865_p3);

assign y_fu_841_p3 = ((or_cond_i497_i_fu_669_p2[0:0] === 1'b1) ? tmp_13_fu_644_p2 : p_p2_i498_i_0_p_assig_fu_833_p3);

always @ (posedge ap_clk) begin
    tmp_9_reg_2513[0] <= 1'b0;
    tmp_65_2_reg_2520[0] <= 1'b0;
end

endmodule //Filter2D
