// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_sobel,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.144000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=1680,HLS_SYN_LUT=4546,HLS_VERSION=2018_3}" *)

module hls_sobel (
        input_V_data_V_dout,
        input_V_data_V_empty_n,
        input_V_data_V_read,
        input_V_keep_V_dout,
        input_V_keep_V_empty_n,
        input_V_keep_V_read,
        input_V_strb_V_dout,
        input_V_strb_V_empty_n,
        input_V_strb_V_read,
        input_V_user_V_dout,
        input_V_user_V_empty_n,
        input_V_user_V_read,
        input_V_last_V_dout,
        input_V_last_V_empty_n,
        input_V_last_V_read,
        input_V_id_V_dout,
        input_V_id_V_empty_n,
        input_V_id_V_read,
        input_V_dest_V_dout,
        input_V_dest_V_empty_n,
        input_V_dest_V_read,
        output_V_data_V_din,
        output_V_data_V_full_n,
        output_V_data_V_write,
        output_V_keep_V_din,
        output_V_keep_V_full_n,
        output_V_keep_V_write,
        output_V_strb_V_din,
        output_V_strb_V_full_n,
        output_V_strb_V_write,
        output_V_user_V_din,
        output_V_user_V_full_n,
        output_V_user_V_write,
        output_V_last_V_din,
        output_V_last_V_full_n,
        output_V_last_V_write,
        output_V_id_V_din,
        output_V_id_V_full_n,
        output_V_id_V_write,
        output_V_dest_V_din,
        output_V_dest_V_full_n,
        output_V_dest_V_write,
        rows,
        cols,
        ap_clk,
        ap_rst
);


input  [23:0] input_V_data_V_dout;
input   input_V_data_V_empty_n;
output   input_V_data_V_read;
input  [2:0] input_V_keep_V_dout;
input   input_V_keep_V_empty_n;
output   input_V_keep_V_read;
input  [2:0] input_V_strb_V_dout;
input   input_V_strb_V_empty_n;
output   input_V_strb_V_read;
input  [0:0] input_V_user_V_dout;
input   input_V_user_V_empty_n;
output   input_V_user_V_read;
input  [0:0] input_V_last_V_dout;
input   input_V_last_V_empty_n;
output   input_V_last_V_read;
input  [0:0] input_V_id_V_dout;
input   input_V_id_V_empty_n;
output   input_V_id_V_read;
input  [0:0] input_V_dest_V_dout;
input   input_V_dest_V_empty_n;
output   input_V_dest_V_read;
output  [23:0] output_V_data_V_din;
input   output_V_data_V_full_n;
output   output_V_data_V_write;
output  [2:0] output_V_keep_V_din;
input   output_V_keep_V_full_n;
output   output_V_keep_V_write;
output  [2:0] output_V_strb_V_din;
input   output_V_strb_V_full_n;
output   output_V_strb_V_write;
output  [0:0] output_V_user_V_din;
input   output_V_user_V_full_n;
output   output_V_user_V_write;
output  [0:0] output_V_last_V_din;
input   output_V_last_V_full_n;
output   output_V_last_V_write;
output  [0:0] output_V_id_V_din;
input   output_V_id_V_full_n;
output   output_V_id_V_write;
output  [0:0] output_V_dest_V_din;
input   output_V_dest_V_full_n;
output   output_V_dest_V_write;
input  [31:0] rows;
input  [31:0] cols;
input   ap_clk;
input   ap_rst;

wire    Block_Mat_exit45_pro_U0_ap_start;
wire    Block_Mat_exit45_pro_U0_ap_done;
wire    Block_Mat_exit45_pro_U0_ap_continue;
wire    Block_Mat_exit45_pro_U0_ap_idle;
wire    Block_Mat_exit45_pro_U0_ap_ready;
wire    Block_Mat_exit45_pro_U0_start_out;
wire    Block_Mat_exit45_pro_U0_start_write;
wire   [31:0] Block_Mat_exit45_pro_U0_img_0_rows_V_out_din;
wire    Block_Mat_exit45_pro_U0_img_0_rows_V_out_write;
wire   [31:0] Block_Mat_exit45_pro_U0_img_0_cols_V_out_din;
wire    Block_Mat_exit45_pro_U0_img_0_cols_V_out_write;
wire   [31:0] Block_Mat_exit45_pro_U0_img_1_rows_V_out_din;
wire    Block_Mat_exit45_pro_U0_img_1_rows_V_out_write;
wire   [31:0] Block_Mat_exit45_pro_U0_img_1_cols_V_out_din;
wire    Block_Mat_exit45_pro_U0_img_1_cols_V_out_write;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire   [31:0] AXIvideo2Mat_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_U0_img_rows_V_out_write;
wire   [31:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    Sobel_U0_ap_start;
wire    Sobel_U0_ap_done;
wire    Sobel_U0_ap_continue;
wire    Sobel_U0_ap_idle;
wire    Sobel_U0_ap_ready;
wire    Sobel_U0_p_src_rows_V_read;
wire    Sobel_U0_p_src_cols_V_read;
wire    Sobel_U0_p_src_data_stream_0_V_read;
wire    Sobel_U0_p_src_data_stream_1_V_read;
wire    Sobel_U0_p_src_data_stream_2_V_read;
wire   [7:0] Sobel_U0_p_dst_data_stream_0_V_din;
wire    Sobel_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Sobel_U0_p_dst_data_stream_1_V_din;
wire    Sobel_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Sobel_U0_p_dst_data_stream_2_V_din;
wire    Sobel_U0_p_dst_data_stream_2_V_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_rows_V_read;
wire    Mat2AXIvideo_U0_img_cols_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [23:0] Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write;
wire   [2:0] Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write;
wire   [2:0] Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write;
wire    ap_sync_continue;
wire    img_0_rows_V_c_full_n;
wire   [31:0] img_0_rows_V_c_dout;
wire    img_0_rows_V_c_empty_n;
wire    img_0_cols_V_c_full_n;
wire   [31:0] img_0_cols_V_c_dout;
wire    img_0_cols_V_c_empty_n;
wire    img_1_rows_V_c_full_n;
wire   [31:0] img_1_rows_V_c_dout;
wire    img_1_rows_V_c_empty_n;
wire    img_1_cols_V_c_full_n;
wire   [31:0] img_1_cols_V_c_dout;
wire    img_1_cols_V_c_empty_n;
wire    img_0_data_stream_0_full_n;
wire   [7:0] img_0_data_stream_0_dout;
wire    img_0_data_stream_0_empty_n;
wire    img_0_data_stream_1_full_n;
wire   [7:0] img_0_data_stream_1_dout;
wire    img_0_data_stream_1_empty_n;
wire    img_0_data_stream_2_full_n;
wire   [7:0] img_0_data_stream_2_dout;
wire    img_0_data_stream_2_empty_n;
wire    img_0_rows_V_c13_full_n;
wire   [31:0] img_0_rows_V_c13_dout;
wire    img_0_rows_V_c13_empty_n;
wire    img_0_cols_V_c14_full_n;
wire   [31:0] img_0_cols_V_c14_dout;
wire    img_0_cols_V_c14_empty_n;
wire    img_1_data_stream_0_full_n;
wire   [7:0] img_1_data_stream_0_dout;
wire    img_1_data_stream_0_empty_n;
wire    img_1_data_stream_1_full_n;
wire   [7:0] img_1_data_stream_1_dout;
wire    img_1_data_stream_1_empty_n;
wire    img_1_data_stream_2_full_n;
wire   [7:0] img_1_data_stream_2_dout;
wire    img_1_data_stream_2_empty_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire   [0:0] start_for_Sobel_U0_din;
wire    start_for_Sobel_U0_full_n;
wire   [0:0] start_for_Sobel_U0_dout;
wire    start_for_Sobel_U0_empty_n;
wire    Sobel_U0_start_full_n;
wire    Sobel_U0_start_write;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

Block_Mat_exit45_pro Block_Mat_exit45_pro_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_Mat_exit45_pro_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(Block_Mat_exit45_pro_U0_ap_done),
    .ap_continue(Block_Mat_exit45_pro_U0_ap_continue),
    .ap_idle(Block_Mat_exit45_pro_U0_ap_idle),
    .ap_ready(Block_Mat_exit45_pro_U0_ap_ready),
    .start_out(Block_Mat_exit45_pro_U0_start_out),
    .start_write(Block_Mat_exit45_pro_U0_start_write),
    .rows(rows),
    .cols(cols),
    .img_0_rows_V_out_din(Block_Mat_exit45_pro_U0_img_0_rows_V_out_din),
    .img_0_rows_V_out_full_n(img_0_rows_V_c_full_n),
    .img_0_rows_V_out_write(Block_Mat_exit45_pro_U0_img_0_rows_V_out_write),
    .img_0_cols_V_out_din(Block_Mat_exit45_pro_U0_img_0_cols_V_out_din),
    .img_0_cols_V_out_full_n(img_0_cols_V_c_full_n),
    .img_0_cols_V_out_write(Block_Mat_exit45_pro_U0_img_0_cols_V_out_write),
    .img_1_rows_V_out_din(Block_Mat_exit45_pro_U0_img_1_rows_V_out_din),
    .img_1_rows_V_out_full_n(img_1_rows_V_c_full_n),
    .img_1_rows_V_out_write(Block_Mat_exit45_pro_U0_img_1_rows_V_out_write),
    .img_1_cols_V_out_din(Block_Mat_exit45_pro_U0_img_1_cols_V_out_din),
    .img_1_cols_V_out_full_n(img_1_cols_V_c_full_n),
    .img_1_cols_V_out_write(Block_Mat_exit45_pro_U0_img_1_cols_V_out_write)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_Sobel_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .AXI_video_strm_V_data_V_dout(input_V_data_V_dout),
    .AXI_video_strm_V_data_V_empty_n(input_V_data_V_empty_n),
    .AXI_video_strm_V_data_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read),
    .AXI_video_strm_V_keep_V_dout(input_V_keep_V_dout),
    .AXI_video_strm_V_keep_V_empty_n(input_V_keep_V_empty_n),
    .AXI_video_strm_V_keep_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read),
    .AXI_video_strm_V_strb_V_dout(input_V_strb_V_dout),
    .AXI_video_strm_V_strb_V_empty_n(input_V_strb_V_empty_n),
    .AXI_video_strm_V_strb_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read),
    .AXI_video_strm_V_user_V_dout(input_V_user_V_dout),
    .AXI_video_strm_V_user_V_empty_n(input_V_user_V_empty_n),
    .AXI_video_strm_V_user_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read),
    .AXI_video_strm_V_last_V_dout(input_V_last_V_dout),
    .AXI_video_strm_V_last_V_empty_n(input_V_last_V_empty_n),
    .AXI_video_strm_V_last_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read),
    .AXI_video_strm_V_id_V_dout(input_V_id_V_dout),
    .AXI_video_strm_V_id_V_empty_n(input_V_id_V_empty_n),
    .AXI_video_strm_V_id_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read),
    .AXI_video_strm_V_dest_V_dout(input_V_dest_V_dout),
    .AXI_video_strm_V_dest_V_empty_n(input_V_dest_V_empty_n),
    .AXI_video_strm_V_dest_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read),
    .img_rows_V_dout(img_0_rows_V_c_dout),
    .img_rows_V_empty_n(img_0_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(img_0_cols_V_c_dout),
    .img_cols_V_empty_n(img_0_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(img_0_data_stream_0_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(img_0_data_stream_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(img_0_data_stream_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(img_0_rows_V_c13_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(img_0_cols_V_c14_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

Sobel Sobel_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Sobel_U0_ap_start),
    .ap_done(Sobel_U0_ap_done),
    .ap_continue(Sobel_U0_ap_continue),
    .ap_idle(Sobel_U0_ap_idle),
    .ap_ready(Sobel_U0_ap_ready),
    .p_src_rows_V_dout(img_0_rows_V_c13_dout),
    .p_src_rows_V_empty_n(img_0_rows_V_c13_empty_n),
    .p_src_rows_V_read(Sobel_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(img_0_cols_V_c14_dout),
    .p_src_cols_V_empty_n(img_0_cols_V_c14_empty_n),
    .p_src_cols_V_read(Sobel_U0_p_src_cols_V_read),
    .p_src_data_stream_0_V_dout(img_0_data_stream_0_dout),
    .p_src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n),
    .p_src_data_stream_0_V_read(Sobel_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(img_0_data_stream_1_dout),
    .p_src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n),
    .p_src_data_stream_1_V_read(Sobel_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(img_0_data_stream_2_dout),
    .p_src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n),
    .p_src_data_stream_2_V_read(Sobel_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_0_V_din(Sobel_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(img_1_data_stream_0_full_n),
    .p_dst_data_stream_0_V_write(Sobel_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Sobel_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(img_1_data_stream_1_full_n),
    .p_dst_data_stream_1_V_write(Sobel_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Sobel_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(img_1_data_stream_2_full_n),
    .p_dst_data_stream_2_V_write(Sobel_U0_p_dst_data_stream_2_V_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_rows_V_dout(img_1_rows_V_c_dout),
    .img_rows_V_empty_n(img_1_rows_V_c_empty_n),
    .img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read),
    .img_cols_V_dout(img_1_cols_V_c_dout),
    .img_cols_V_empty_n(img_1_cols_V_c_empty_n),
    .img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read),
    .img_data_stream_0_V_dout(img_1_data_stream_0_dout),
    .img_data_stream_0_V_empty_n(img_1_data_stream_0_empty_n),
    .img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read),
    .img_data_stream_1_V_dout(img_1_data_stream_1_dout),
    .img_data_stream_1_V_empty_n(img_1_data_stream_1_empty_n),
    .img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read),
    .img_data_stream_2_V_dout(img_1_data_stream_2_dout),
    .img_data_stream_2_V_empty_n(img_1_data_stream_2_empty_n),
    .img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read),
    .AXI_video_strm_V_data_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din),
    .AXI_video_strm_V_data_V_full_n(output_V_data_V_full_n),
    .AXI_video_strm_V_data_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write),
    .AXI_video_strm_V_keep_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din),
    .AXI_video_strm_V_keep_V_full_n(output_V_keep_V_full_n),
    .AXI_video_strm_V_keep_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write),
    .AXI_video_strm_V_strb_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din),
    .AXI_video_strm_V_strb_V_full_n(output_V_strb_V_full_n),
    .AXI_video_strm_V_strb_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write),
    .AXI_video_strm_V_user_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din),
    .AXI_video_strm_V_user_V_full_n(output_V_user_V_full_n),
    .AXI_video_strm_V_user_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write),
    .AXI_video_strm_V_last_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din),
    .AXI_video_strm_V_last_V_full_n(output_V_last_V_full_n),
    .AXI_video_strm_V_last_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write),
    .AXI_video_strm_V_id_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din),
    .AXI_video_strm_V_id_V_full_n(output_V_id_V_full_n),
    .AXI_video_strm_V_id_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write),
    .AXI_video_strm_V_dest_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din),
    .AXI_video_strm_V_dest_V_full_n(output_V_dest_V_full_n),
    .AXI_video_strm_V_dest_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write)
);

fifo_w32_d2_A img_0_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit45_pro_U0_img_0_rows_V_out_din),
    .if_full_n(img_0_rows_V_c_full_n),
    .if_write(Block_Mat_exit45_pro_U0_img_0_rows_V_out_write),
    .if_dout(img_0_rows_V_c_dout),
    .if_empty_n(img_0_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w32_d2_A img_0_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit45_pro_U0_img_0_cols_V_out_din),
    .if_full_n(img_0_cols_V_c_full_n),
    .if_write(Block_Mat_exit45_pro_U0_img_0_cols_V_out_write),
    .if_dout(img_0_cols_V_c_dout),
    .if_empty_n(img_0_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w32_d4_A img_1_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit45_pro_U0_img_1_rows_V_out_din),
    .if_full_n(img_1_rows_V_c_full_n),
    .if_write(Block_Mat_exit45_pro_U0_img_1_rows_V_out_write),
    .if_dout(img_1_rows_V_c_dout),
    .if_empty_n(img_1_rows_V_c_empty_n),
    .if_read(Mat2AXIvideo_U0_img_rows_V_read)
);

fifo_w32_d4_A img_1_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit45_pro_U0_img_1_cols_V_out_din),
    .if_full_n(img_1_cols_V_c_full_n),
    .if_write(Block_Mat_exit45_pro_U0_img_1_cols_V_out_write),
    .if_dout(img_1_cols_V_c_dout),
    .if_empty_n(img_1_cols_V_c_empty_n),
    .if_read(Mat2AXIvideo_U0_img_cols_V_read)
);

fifo_w8_d2_A img_0_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(img_0_data_stream_0_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(img_0_data_stream_0_dout),
    .if_empty_n(img_0_data_stream_0_empty_n),
    .if_read(Sobel_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_0_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(img_0_data_stream_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(img_0_data_stream_1_dout),
    .if_empty_n(img_0_data_stream_1_empty_n),
    .if_read(Sobel_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_0_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(img_0_data_stream_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(img_0_data_stream_2_dout),
    .if_empty_n(img_0_data_stream_2_empty_n),
    .if_read(Sobel_U0_p_src_data_stream_2_V_read)
);

fifo_w32_d2_A img_0_rows_V_c13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .if_full_n(img_0_rows_V_c13_full_n),
    .if_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .if_dout(img_0_rows_V_c13_dout),
    .if_empty_n(img_0_rows_V_c13_empty_n),
    .if_read(Sobel_U0_p_src_rows_V_read)
);

fifo_w32_d2_A img_0_cols_V_c14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(img_0_cols_V_c14_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(img_0_cols_V_c14_dout),
    .if_empty_n(img_0_cols_V_c14_empty_n),
    .if_read(Sobel_U0_p_src_cols_V_read)
);

fifo_w8_d2_A img_1_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_U0_p_dst_data_stream_0_V_din),
    .if_full_n(img_1_data_stream_0_full_n),
    .if_write(Sobel_U0_p_dst_data_stream_0_V_write),
    .if_dout(img_1_data_stream_0_dout),
    .if_empty_n(img_1_data_stream_0_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read)
);

fifo_w8_d2_A img_1_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_U0_p_dst_data_stream_1_V_din),
    .if_full_n(img_1_data_stream_1_full_n),
    .if_write(Sobel_U0_p_dst_data_stream_1_V_write),
    .if_dout(img_1_data_stream_1_dout),
    .if_empty_n(img_1_data_stream_1_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read)
);

fifo_w8_d2_A img_1_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_U0_p_dst_data_stream_2_V_din),
    .if_full_n(img_1_data_stream_2_full_n),
    .if_write(Sobel_U0_p_dst_data_stream_2_V_write),
    .if_dout(img_1_data_stream_2_dout),
    .if_empty_n(img_1_data_stream_2_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read)
);

start_for_Mat2AXIlbW start_for_Mat2AXIlbW_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(Block_Mat_exit45_pro_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

start_for_Sobel_U0 start_for_Sobel_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_U0_din),
    .if_full_n(start_for_Sobel_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_Sobel_U0_dout),
    .if_empty_n(start_for_Sobel_U0_empty_n),
    .if_read(Sobel_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = 1'b1;

assign Block_Mat_exit45_pro_U0_ap_continue = 1'b1;

assign Block_Mat_exit45_pro_U0_ap_start = 1'b1;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign Sobel_U0_ap_continue = 1'b1;

assign Sobel_U0_ap_start = start_for_Sobel_U0_empty_n;

assign Sobel_U0_start_full_n = 1'b1;

assign Sobel_U0_start_write = 1'b0;

assign ap_sync_continue = 1'b0;

assign input_V_data_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read;

assign input_V_dest_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read;

assign input_V_id_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read;

assign input_V_keep_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read;

assign input_V_last_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read;

assign input_V_strb_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read;

assign input_V_user_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read;

assign output_V_data_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din;

assign output_V_data_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write;

assign output_V_dest_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din;

assign output_V_dest_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write;

assign output_V_id_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din;

assign output_V_id_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write;

assign output_V_keep_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din;

assign output_V_keep_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write;

assign output_V_last_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din;

assign output_V_last_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write;

assign output_V_strb_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din;

assign output_V_strb_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write;

assign output_V_user_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din;

assign output_V_user_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_Sobel_U0_din = 1'b1;

endmodule //hls_sobel
