// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hls_sobel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hls_sobel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> hls_sobel::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<3> hls_sobel::ap_const_lv3_0 = "000";
const sc_lv<1> hls_sobel::ap_const_lv1_0 = "0";
const sc_logic hls_sobel::ap_const_logic_1 = sc_dt::Log_1;

hls_sobel::hls_sobel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Block_Mat_exit45_pro_U0 = new Block_Mat_exit45_pro("Block_Mat_exit45_pro_U0");
    Block_Mat_exit45_pro_U0->ap_clk(ap_clk);
    Block_Mat_exit45_pro_U0->ap_rst(ap_rst);
    Block_Mat_exit45_pro_U0->ap_start(Block_Mat_exit45_pro_U0_ap_start);
    Block_Mat_exit45_pro_U0->start_full_n(start_for_Mat2AXIvideo_U0_full_n);
    Block_Mat_exit45_pro_U0->ap_done(Block_Mat_exit45_pro_U0_ap_done);
    Block_Mat_exit45_pro_U0->ap_continue(Block_Mat_exit45_pro_U0_ap_continue);
    Block_Mat_exit45_pro_U0->ap_idle(Block_Mat_exit45_pro_U0_ap_idle);
    Block_Mat_exit45_pro_U0->ap_ready(Block_Mat_exit45_pro_U0_ap_ready);
    Block_Mat_exit45_pro_U0->start_out(Block_Mat_exit45_pro_U0_start_out);
    Block_Mat_exit45_pro_U0->start_write(Block_Mat_exit45_pro_U0_start_write);
    Block_Mat_exit45_pro_U0->rows(rows);
    Block_Mat_exit45_pro_U0->cols(cols);
    Block_Mat_exit45_pro_U0->img_0_rows_V_out_din(Block_Mat_exit45_pro_U0_img_0_rows_V_out_din);
    Block_Mat_exit45_pro_U0->img_0_rows_V_out_full_n(img_0_rows_V_c_full_n);
    Block_Mat_exit45_pro_U0->img_0_rows_V_out_write(Block_Mat_exit45_pro_U0_img_0_rows_V_out_write);
    Block_Mat_exit45_pro_U0->img_0_cols_V_out_din(Block_Mat_exit45_pro_U0_img_0_cols_V_out_din);
    Block_Mat_exit45_pro_U0->img_0_cols_V_out_full_n(img_0_cols_V_c_full_n);
    Block_Mat_exit45_pro_U0->img_0_cols_V_out_write(Block_Mat_exit45_pro_U0_img_0_cols_V_out_write);
    Block_Mat_exit45_pro_U0->img_1_rows_V_out_din(Block_Mat_exit45_pro_U0_img_1_rows_V_out_din);
    Block_Mat_exit45_pro_U0->img_1_rows_V_out_full_n(img_1_rows_V_c_full_n);
    Block_Mat_exit45_pro_U0->img_1_rows_V_out_write(Block_Mat_exit45_pro_U0_img_1_rows_V_out_write);
    Block_Mat_exit45_pro_U0->img_1_cols_V_out_din(Block_Mat_exit45_pro_U0_img_1_cols_V_out_din);
    Block_Mat_exit45_pro_U0->img_1_cols_V_out_full_n(img_1_cols_V_c_full_n);
    Block_Mat_exit45_pro_U0->img_1_cols_V_out_write(Block_Mat_exit45_pro_U0_img_1_cols_V_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_Sobel_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->AXI_video_strm_V_data_V_dout(input_V_data_V_dout);
    AXIvideo2Mat_U0->AXI_video_strm_V_data_V_empty_n(input_V_data_V_empty_n);
    AXIvideo2Mat_U0->AXI_video_strm_V_data_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read);
    AXIvideo2Mat_U0->AXI_video_strm_V_keep_V_dout(input_V_keep_V_dout);
    AXIvideo2Mat_U0->AXI_video_strm_V_keep_V_empty_n(input_V_keep_V_empty_n);
    AXIvideo2Mat_U0->AXI_video_strm_V_keep_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read);
    AXIvideo2Mat_U0->AXI_video_strm_V_strb_V_dout(input_V_strb_V_dout);
    AXIvideo2Mat_U0->AXI_video_strm_V_strb_V_empty_n(input_V_strb_V_empty_n);
    AXIvideo2Mat_U0->AXI_video_strm_V_strb_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read);
    AXIvideo2Mat_U0->AXI_video_strm_V_user_V_dout(input_V_user_V_dout);
    AXIvideo2Mat_U0->AXI_video_strm_V_user_V_empty_n(input_V_user_V_empty_n);
    AXIvideo2Mat_U0->AXI_video_strm_V_user_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read);
    AXIvideo2Mat_U0->AXI_video_strm_V_last_V_dout(input_V_last_V_dout);
    AXIvideo2Mat_U0->AXI_video_strm_V_last_V_empty_n(input_V_last_V_empty_n);
    AXIvideo2Mat_U0->AXI_video_strm_V_last_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read);
    AXIvideo2Mat_U0->AXI_video_strm_V_id_V_dout(input_V_id_V_dout);
    AXIvideo2Mat_U0->AXI_video_strm_V_id_V_empty_n(input_V_id_V_empty_n);
    AXIvideo2Mat_U0->AXI_video_strm_V_id_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read);
    AXIvideo2Mat_U0->AXI_video_strm_V_dest_V_dout(input_V_dest_V_dout);
    AXIvideo2Mat_U0->AXI_video_strm_V_dest_V_empty_n(input_V_dest_V_empty_n);
    AXIvideo2Mat_U0->AXI_video_strm_V_dest_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read);
    AXIvideo2Mat_U0->img_rows_V_dout(img_0_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(img_0_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(img_0_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(img_0_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    AXIvideo2Mat_U0->img_data_stream_0_V_full_n(img_0_data_stream_0_full_n);
    AXIvideo2Mat_U0->img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    AXIvideo2Mat_U0->img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    AXIvideo2Mat_U0->img_data_stream_1_V_full_n(img_0_data_stream_1_full_n);
    AXIvideo2Mat_U0->img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    AXIvideo2Mat_U0->img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    AXIvideo2Mat_U0->img_data_stream_2_V_full_n(img_0_data_stream_2_full_n);
    AXIvideo2Mat_U0->img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(img_0_rows_V_c13_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(img_0_cols_V_c14_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    Sobel_U0 = new Sobel("Sobel_U0");
    Sobel_U0->ap_clk(ap_clk);
    Sobel_U0->ap_rst(ap_rst);
    Sobel_U0->ap_start(Sobel_U0_ap_start);
    Sobel_U0->ap_done(Sobel_U0_ap_done);
    Sobel_U0->ap_continue(Sobel_U0_ap_continue);
    Sobel_U0->ap_idle(Sobel_U0_ap_idle);
    Sobel_U0->ap_ready(Sobel_U0_ap_ready);
    Sobel_U0->p_src_rows_V_dout(img_0_rows_V_c13_dout);
    Sobel_U0->p_src_rows_V_empty_n(img_0_rows_V_c13_empty_n);
    Sobel_U0->p_src_rows_V_read(Sobel_U0_p_src_rows_V_read);
    Sobel_U0->p_src_cols_V_dout(img_0_cols_V_c14_dout);
    Sobel_U0->p_src_cols_V_empty_n(img_0_cols_V_c14_empty_n);
    Sobel_U0->p_src_cols_V_read(Sobel_U0_p_src_cols_V_read);
    Sobel_U0->p_src_data_stream_0_V_dout(img_0_data_stream_0_dout);
    Sobel_U0->p_src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n);
    Sobel_U0->p_src_data_stream_0_V_read(Sobel_U0_p_src_data_stream_0_V_read);
    Sobel_U0->p_src_data_stream_1_V_dout(img_0_data_stream_1_dout);
    Sobel_U0->p_src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n);
    Sobel_U0->p_src_data_stream_1_V_read(Sobel_U0_p_src_data_stream_1_V_read);
    Sobel_U0->p_src_data_stream_2_V_dout(img_0_data_stream_2_dout);
    Sobel_U0->p_src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n);
    Sobel_U0->p_src_data_stream_2_V_read(Sobel_U0_p_src_data_stream_2_V_read);
    Sobel_U0->p_dst_data_stream_0_V_din(Sobel_U0_p_dst_data_stream_0_V_din);
    Sobel_U0->p_dst_data_stream_0_V_full_n(img_1_data_stream_0_full_n);
    Sobel_U0->p_dst_data_stream_0_V_write(Sobel_U0_p_dst_data_stream_0_V_write);
    Sobel_U0->p_dst_data_stream_1_V_din(Sobel_U0_p_dst_data_stream_1_V_din);
    Sobel_U0->p_dst_data_stream_1_V_full_n(img_1_data_stream_1_full_n);
    Sobel_U0->p_dst_data_stream_1_V_write(Sobel_U0_p_dst_data_stream_1_V_write);
    Sobel_U0->p_dst_data_stream_2_V_din(Sobel_U0_p_dst_data_stream_2_V_din);
    Sobel_U0->p_dst_data_stream_2_V_full_n(img_1_data_stream_2_full_n);
    Sobel_U0->p_dst_data_stream_2_V_write(Sobel_U0_p_dst_data_stream_2_V_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_rows_V_dout(img_1_rows_V_c_dout);
    Mat2AXIvideo_U0->img_rows_V_empty_n(img_1_rows_V_c_empty_n);
    Mat2AXIvideo_U0->img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read);
    Mat2AXIvideo_U0->img_cols_V_dout(img_1_cols_V_c_dout);
    Mat2AXIvideo_U0->img_cols_V_empty_n(img_1_cols_V_c_empty_n);
    Mat2AXIvideo_U0->img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read);
    Mat2AXIvideo_U0->img_data_stream_0_V_dout(img_1_data_stream_0_dout);
    Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(img_1_data_stream_0_empty_n);
    Mat2AXIvideo_U0->img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    Mat2AXIvideo_U0->img_data_stream_1_V_dout(img_1_data_stream_1_dout);
    Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(img_1_data_stream_1_empty_n);
    Mat2AXIvideo_U0->img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    Mat2AXIvideo_U0->img_data_stream_2_V_dout(img_1_data_stream_2_dout);
    Mat2AXIvideo_U0->img_data_stream_2_V_empty_n(img_1_data_stream_2_empty_n);
    Mat2AXIvideo_U0->img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    Mat2AXIvideo_U0->AXI_video_strm_V_data_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din);
    Mat2AXIvideo_U0->AXI_video_strm_V_data_V_full_n(output_V_data_V_full_n);
    Mat2AXIvideo_U0->AXI_video_strm_V_data_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write);
    Mat2AXIvideo_U0->AXI_video_strm_V_keep_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din);
    Mat2AXIvideo_U0->AXI_video_strm_V_keep_V_full_n(output_V_keep_V_full_n);
    Mat2AXIvideo_U0->AXI_video_strm_V_keep_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write);
    Mat2AXIvideo_U0->AXI_video_strm_V_strb_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din);
    Mat2AXIvideo_U0->AXI_video_strm_V_strb_V_full_n(output_V_strb_V_full_n);
    Mat2AXIvideo_U0->AXI_video_strm_V_strb_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write);
    Mat2AXIvideo_U0->AXI_video_strm_V_user_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din);
    Mat2AXIvideo_U0->AXI_video_strm_V_user_V_full_n(output_V_user_V_full_n);
    Mat2AXIvideo_U0->AXI_video_strm_V_user_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write);
    Mat2AXIvideo_U0->AXI_video_strm_V_last_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din);
    Mat2AXIvideo_U0->AXI_video_strm_V_last_V_full_n(output_V_last_V_full_n);
    Mat2AXIvideo_U0->AXI_video_strm_V_last_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write);
    Mat2AXIvideo_U0->AXI_video_strm_V_id_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din);
    Mat2AXIvideo_U0->AXI_video_strm_V_id_V_full_n(output_V_id_V_full_n);
    Mat2AXIvideo_U0->AXI_video_strm_V_id_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write);
    Mat2AXIvideo_U0->AXI_video_strm_V_dest_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din);
    Mat2AXIvideo_U0->AXI_video_strm_V_dest_V_full_n(output_V_dest_V_full_n);
    Mat2AXIvideo_U0->AXI_video_strm_V_dest_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write);
    img_0_rows_V_c_U = new fifo_w32_d2_A("img_0_rows_V_c_U");
    img_0_rows_V_c_U->clk(ap_clk);
    img_0_rows_V_c_U->reset(ap_rst);
    img_0_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_din(Block_Mat_exit45_pro_U0_img_0_rows_V_out_din);
    img_0_rows_V_c_U->if_full_n(img_0_rows_V_c_full_n);
    img_0_rows_V_c_U->if_write(Block_Mat_exit45_pro_U0_img_0_rows_V_out_write);
    img_0_rows_V_c_U->if_dout(img_0_rows_V_c_dout);
    img_0_rows_V_c_U->if_empty_n(img_0_rows_V_c_empty_n);
    img_0_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    img_0_cols_V_c_U = new fifo_w32_d2_A("img_0_cols_V_c_U");
    img_0_cols_V_c_U->clk(ap_clk);
    img_0_cols_V_c_U->reset(ap_rst);
    img_0_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_din(Block_Mat_exit45_pro_U0_img_0_cols_V_out_din);
    img_0_cols_V_c_U->if_full_n(img_0_cols_V_c_full_n);
    img_0_cols_V_c_U->if_write(Block_Mat_exit45_pro_U0_img_0_cols_V_out_write);
    img_0_cols_V_c_U->if_dout(img_0_cols_V_c_dout);
    img_0_cols_V_c_U->if_empty_n(img_0_cols_V_c_empty_n);
    img_0_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    img_1_rows_V_c_U = new fifo_w32_d4_A("img_1_rows_V_c_U");
    img_1_rows_V_c_U->clk(ap_clk);
    img_1_rows_V_c_U->reset(ap_rst);
    img_1_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_din(Block_Mat_exit45_pro_U0_img_1_rows_V_out_din);
    img_1_rows_V_c_U->if_full_n(img_1_rows_V_c_full_n);
    img_1_rows_V_c_U->if_write(Block_Mat_exit45_pro_U0_img_1_rows_V_out_write);
    img_1_rows_V_c_U->if_dout(img_1_rows_V_c_dout);
    img_1_rows_V_c_U->if_empty_n(img_1_rows_V_c_empty_n);
    img_1_rows_V_c_U->if_read(Mat2AXIvideo_U0_img_rows_V_read);
    img_1_cols_V_c_U = new fifo_w32_d4_A("img_1_cols_V_c_U");
    img_1_cols_V_c_U->clk(ap_clk);
    img_1_cols_V_c_U->reset(ap_rst);
    img_1_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_din(Block_Mat_exit45_pro_U0_img_1_cols_V_out_din);
    img_1_cols_V_c_U->if_full_n(img_1_cols_V_c_full_n);
    img_1_cols_V_c_U->if_write(Block_Mat_exit45_pro_U0_img_1_cols_V_out_write);
    img_1_cols_V_c_U->if_dout(img_1_cols_V_c_dout);
    img_1_cols_V_c_U->if_empty_n(img_1_cols_V_c_empty_n);
    img_1_cols_V_c_U->if_read(Mat2AXIvideo_U0_img_cols_V_read);
    img_0_data_stream_0_U = new fifo_w8_d2_A("img_0_data_stream_0_U");
    img_0_data_stream_0_U->clk(ap_clk);
    img_0_data_stream_0_U->reset(ap_rst);
    img_0_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    img_0_data_stream_0_U->if_full_n(img_0_data_stream_0_full_n);
    img_0_data_stream_0_U->if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    img_0_data_stream_0_U->if_dout(img_0_data_stream_0_dout);
    img_0_data_stream_0_U->if_empty_n(img_0_data_stream_0_empty_n);
    img_0_data_stream_0_U->if_read(Sobel_U0_p_src_data_stream_0_V_read);
    img_0_data_stream_1_U = new fifo_w8_d2_A("img_0_data_stream_1_U");
    img_0_data_stream_1_U->clk(ap_clk);
    img_0_data_stream_1_U->reset(ap_rst);
    img_0_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    img_0_data_stream_1_U->if_full_n(img_0_data_stream_1_full_n);
    img_0_data_stream_1_U->if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    img_0_data_stream_1_U->if_dout(img_0_data_stream_1_dout);
    img_0_data_stream_1_U->if_empty_n(img_0_data_stream_1_empty_n);
    img_0_data_stream_1_U->if_read(Sobel_U0_p_src_data_stream_1_V_read);
    img_0_data_stream_2_U = new fifo_w8_d2_A("img_0_data_stream_2_U");
    img_0_data_stream_2_U->clk(ap_clk);
    img_0_data_stream_2_U->reset(ap_rst);
    img_0_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    img_0_data_stream_2_U->if_full_n(img_0_data_stream_2_full_n);
    img_0_data_stream_2_U->if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    img_0_data_stream_2_U->if_dout(img_0_data_stream_2_dout);
    img_0_data_stream_2_U->if_empty_n(img_0_data_stream_2_empty_n);
    img_0_data_stream_2_U->if_read(Sobel_U0_p_src_data_stream_2_V_read);
    img_0_rows_V_c13_U = new fifo_w32_d2_A("img_0_rows_V_c13_U");
    img_0_rows_V_c13_U->clk(ap_clk);
    img_0_rows_V_c13_U->reset(ap_rst);
    img_0_rows_V_c13_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c13_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c13_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    img_0_rows_V_c13_U->if_full_n(img_0_rows_V_c13_full_n);
    img_0_rows_V_c13_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    img_0_rows_V_c13_U->if_dout(img_0_rows_V_c13_dout);
    img_0_rows_V_c13_U->if_empty_n(img_0_rows_V_c13_empty_n);
    img_0_rows_V_c13_U->if_read(Sobel_U0_p_src_rows_V_read);
    img_0_cols_V_c14_U = new fifo_w32_d2_A("img_0_cols_V_c14_U");
    img_0_cols_V_c14_U->clk(ap_clk);
    img_0_cols_V_c14_U->reset(ap_rst);
    img_0_cols_V_c14_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c14_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c14_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    img_0_cols_V_c14_U->if_full_n(img_0_cols_V_c14_full_n);
    img_0_cols_V_c14_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    img_0_cols_V_c14_U->if_dout(img_0_cols_V_c14_dout);
    img_0_cols_V_c14_U->if_empty_n(img_0_cols_V_c14_empty_n);
    img_0_cols_V_c14_U->if_read(Sobel_U0_p_src_cols_V_read);
    img_1_data_stream_0_U = new fifo_w8_d2_A("img_1_data_stream_0_U");
    img_1_data_stream_0_U->clk(ap_clk);
    img_1_data_stream_0_U->reset(ap_rst);
    img_1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_din(Sobel_U0_p_dst_data_stream_0_V_din);
    img_1_data_stream_0_U->if_full_n(img_1_data_stream_0_full_n);
    img_1_data_stream_0_U->if_write(Sobel_U0_p_dst_data_stream_0_V_write);
    img_1_data_stream_0_U->if_dout(img_1_data_stream_0_dout);
    img_1_data_stream_0_U->if_empty_n(img_1_data_stream_0_empty_n);
    img_1_data_stream_0_U->if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    img_1_data_stream_1_U = new fifo_w8_d2_A("img_1_data_stream_1_U");
    img_1_data_stream_1_U->clk(ap_clk);
    img_1_data_stream_1_U->reset(ap_rst);
    img_1_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_1_U->if_din(Sobel_U0_p_dst_data_stream_1_V_din);
    img_1_data_stream_1_U->if_full_n(img_1_data_stream_1_full_n);
    img_1_data_stream_1_U->if_write(Sobel_U0_p_dst_data_stream_1_V_write);
    img_1_data_stream_1_U->if_dout(img_1_data_stream_1_dout);
    img_1_data_stream_1_U->if_empty_n(img_1_data_stream_1_empty_n);
    img_1_data_stream_1_U->if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    img_1_data_stream_2_U = new fifo_w8_d2_A("img_1_data_stream_2_U");
    img_1_data_stream_2_U->clk(ap_clk);
    img_1_data_stream_2_U->reset(ap_rst);
    img_1_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_2_U->if_din(Sobel_U0_p_dst_data_stream_2_V_din);
    img_1_data_stream_2_U->if_full_n(img_1_data_stream_2_full_n);
    img_1_data_stream_2_U->if_write(Sobel_U0_p_dst_data_stream_2_V_write);
    img_1_data_stream_2_U->if_dout(img_1_data_stream_2_dout);
    img_1_data_stream_2_U->if_empty_n(img_1_data_stream_2_empty_n);
    img_1_data_stream_2_U->if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    start_for_Mat2AXIlbW_U = new start_for_Mat2AXIlbW("start_for_Mat2AXIlbW_U");
    start_for_Mat2AXIlbW_U->clk(ap_clk);
    start_for_Mat2AXIlbW_U->reset(ap_rst);
    start_for_Mat2AXIlbW_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXIlbW_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXIlbW_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXIlbW_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXIlbW_U->if_write(Block_Mat_exit45_pro_U0_start_write);
    start_for_Mat2AXIlbW_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXIlbW_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXIlbW_U->if_read(Mat2AXIvideo_U0_ap_ready);
    start_for_Sobel_U0_U = new start_for_Sobel_U0("start_for_Sobel_U0_U");
    start_for_Sobel_U0_U->clk(ap_clk);
    start_for_Sobel_U0_U->reset(ap_rst);
    start_for_Sobel_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Sobel_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Sobel_U0_U->if_din(start_for_Sobel_U0_din);
    start_for_Sobel_U0_U->if_full_n(start_for_Sobel_U0_full_n);
    start_for_Sobel_U0_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_Sobel_U0_U->if_dout(start_for_Sobel_U0_dout);
    start_for_Sobel_U0_U->if_empty_n(start_for_Sobel_U0_empty_n);
    start_for_Sobel_U0_U->if_read(Sobel_U0_ap_ready);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);

    SC_METHOD(thread_Block_Mat_exit45_pro_U0_ap_continue);

    SC_METHOD(thread_Block_Mat_exit45_pro_U0_ap_start);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_Sobel_U0_ap_continue);

    SC_METHOD(thread_Sobel_U0_ap_start);
    sensitive << ( start_for_Sobel_U0_empty_n );

    SC_METHOD(thread_Sobel_U0_start_full_n);

    SC_METHOD(thread_Sobel_U0_start_write);

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_input_V_data_V_read);
    sensitive << ( AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read );

    SC_METHOD(thread_input_V_dest_V_read);
    sensitive << ( AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read );

    SC_METHOD(thread_input_V_id_V_read);
    sensitive << ( AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read );

    SC_METHOD(thread_input_V_keep_V_read);
    sensitive << ( AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read );

    SC_METHOD(thread_input_V_last_V_read);
    sensitive << ( AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read );

    SC_METHOD(thread_input_V_strb_V_read);
    sensitive << ( AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read );

    SC_METHOD(thread_input_V_user_V_read);
    sensitive << ( AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read );

    SC_METHOD(thread_output_V_data_V_din);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din );

    SC_METHOD(thread_output_V_data_V_write);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write );

    SC_METHOD(thread_output_V_dest_V_din);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din );

    SC_METHOD(thread_output_V_dest_V_write);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write );

    SC_METHOD(thread_output_V_id_V_din);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din );

    SC_METHOD(thread_output_V_id_V_write);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write );

    SC_METHOD(thread_output_V_keep_V_din);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din );

    SC_METHOD(thread_output_V_keep_V_write);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write );

    SC_METHOD(thread_output_V_last_V_din);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din );

    SC_METHOD(thread_output_V_last_V_write);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write );

    SC_METHOD(thread_output_V_strb_V_din);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din );

    SC_METHOD(thread_output_V_strb_V_write);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write );

    SC_METHOD(thread_output_V_user_V_din);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din );

    SC_METHOD(thread_output_V_user_V_write);
    sensitive << ( Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write );

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_Sobel_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hls_sobel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, input_V_data_V_dout, "(port)input_V_data_V_dout");
    sc_trace(mVcdFile, input_V_data_V_empty_n, "(port)input_V_data_V_empty_n");
    sc_trace(mVcdFile, input_V_data_V_read, "(port)input_V_data_V_read");
    sc_trace(mVcdFile, input_V_keep_V_dout, "(port)input_V_keep_V_dout");
    sc_trace(mVcdFile, input_V_keep_V_empty_n, "(port)input_V_keep_V_empty_n");
    sc_trace(mVcdFile, input_V_keep_V_read, "(port)input_V_keep_V_read");
    sc_trace(mVcdFile, input_V_strb_V_dout, "(port)input_V_strb_V_dout");
    sc_trace(mVcdFile, input_V_strb_V_empty_n, "(port)input_V_strb_V_empty_n");
    sc_trace(mVcdFile, input_V_strb_V_read, "(port)input_V_strb_V_read");
    sc_trace(mVcdFile, input_V_user_V_dout, "(port)input_V_user_V_dout");
    sc_trace(mVcdFile, input_V_user_V_empty_n, "(port)input_V_user_V_empty_n");
    sc_trace(mVcdFile, input_V_user_V_read, "(port)input_V_user_V_read");
    sc_trace(mVcdFile, input_V_last_V_dout, "(port)input_V_last_V_dout");
    sc_trace(mVcdFile, input_V_last_V_empty_n, "(port)input_V_last_V_empty_n");
    sc_trace(mVcdFile, input_V_last_V_read, "(port)input_V_last_V_read");
    sc_trace(mVcdFile, input_V_id_V_dout, "(port)input_V_id_V_dout");
    sc_trace(mVcdFile, input_V_id_V_empty_n, "(port)input_V_id_V_empty_n");
    sc_trace(mVcdFile, input_V_id_V_read, "(port)input_V_id_V_read");
    sc_trace(mVcdFile, input_V_dest_V_dout, "(port)input_V_dest_V_dout");
    sc_trace(mVcdFile, input_V_dest_V_empty_n, "(port)input_V_dest_V_empty_n");
    sc_trace(mVcdFile, input_V_dest_V_read, "(port)input_V_dest_V_read");
    sc_trace(mVcdFile, output_V_data_V_din, "(port)output_V_data_V_din");
    sc_trace(mVcdFile, output_V_data_V_full_n, "(port)output_V_data_V_full_n");
    sc_trace(mVcdFile, output_V_data_V_write, "(port)output_V_data_V_write");
    sc_trace(mVcdFile, output_V_keep_V_din, "(port)output_V_keep_V_din");
    sc_trace(mVcdFile, output_V_keep_V_full_n, "(port)output_V_keep_V_full_n");
    sc_trace(mVcdFile, output_V_keep_V_write, "(port)output_V_keep_V_write");
    sc_trace(mVcdFile, output_V_strb_V_din, "(port)output_V_strb_V_din");
    sc_trace(mVcdFile, output_V_strb_V_full_n, "(port)output_V_strb_V_full_n");
    sc_trace(mVcdFile, output_V_strb_V_write, "(port)output_V_strb_V_write");
    sc_trace(mVcdFile, output_V_user_V_din, "(port)output_V_user_V_din");
    sc_trace(mVcdFile, output_V_user_V_full_n, "(port)output_V_user_V_full_n");
    sc_trace(mVcdFile, output_V_user_V_write, "(port)output_V_user_V_write");
    sc_trace(mVcdFile, output_V_last_V_din, "(port)output_V_last_V_din");
    sc_trace(mVcdFile, output_V_last_V_full_n, "(port)output_V_last_V_full_n");
    sc_trace(mVcdFile, output_V_last_V_write, "(port)output_V_last_V_write");
    sc_trace(mVcdFile, output_V_id_V_din, "(port)output_V_id_V_din");
    sc_trace(mVcdFile, output_V_id_V_full_n, "(port)output_V_id_V_full_n");
    sc_trace(mVcdFile, output_V_id_V_write, "(port)output_V_id_V_write");
    sc_trace(mVcdFile, output_V_dest_V_din, "(port)output_V_dest_V_din");
    sc_trace(mVcdFile, output_V_dest_V_full_n, "(port)output_V_dest_V_full_n");
    sc_trace(mVcdFile, output_V_dest_V_write, "(port)output_V_dest_V_write");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_start, "Block_Mat_exit45_pro_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_done, "Block_Mat_exit45_pro_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_continue, "Block_Mat_exit45_pro_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_idle, "Block_Mat_exit45_pro_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_ap_ready, "Block_Mat_exit45_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_start_out, "Block_Mat_exit45_pro_U0_start_out");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_start_write, "Block_Mat_exit45_pro_U0_start_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_0_rows_V_out_din, "Block_Mat_exit45_pro_U0_img_0_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_0_rows_V_out_write, "Block_Mat_exit45_pro_U0_img_0_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_0_cols_V_out_din, "Block_Mat_exit45_pro_U0_img_0_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_0_cols_V_out_write, "Block_Mat_exit45_pro_U0_img_0_cols_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_rows_V_out_din, "Block_Mat_exit45_pro_U0_img_1_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_rows_V_out_write, "Block_Mat_exit45_pro_U0_img_1_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_cols_V_out_din, "Block_Mat_exit45_pro_U0_img_1_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit45_pro_U0_img_1_cols_V_out_write, "Block_Mat_exit45_pro_U0_img_1_cols_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read, "AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read, "AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read, "AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read, "AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read, "AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read, "AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read, "AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_din, "AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_write, "AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_din, "AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_write, "AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_din, "AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_write, "AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, Sobel_U0_ap_start, "Sobel_U0_ap_start");
    sc_trace(mVcdFile, Sobel_U0_ap_done, "Sobel_U0_ap_done");
    sc_trace(mVcdFile, Sobel_U0_ap_continue, "Sobel_U0_ap_continue");
    sc_trace(mVcdFile, Sobel_U0_ap_idle, "Sobel_U0_ap_idle");
    sc_trace(mVcdFile, Sobel_U0_ap_ready, "Sobel_U0_ap_ready");
    sc_trace(mVcdFile, Sobel_U0_p_src_rows_V_read, "Sobel_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, Sobel_U0_p_src_cols_V_read, "Sobel_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, Sobel_U0_p_src_data_stream_0_V_read, "Sobel_U0_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, Sobel_U0_p_src_data_stream_1_V_read, "Sobel_U0_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, Sobel_U0_p_src_data_stream_2_V_read, "Sobel_U0_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_0_V_din, "Sobel_U0_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_0_V_write, "Sobel_U0_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_1_V_din, "Sobel_U0_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_1_V_write, "Sobel_U0_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_2_V_din, "Sobel_U0_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_2_V_write, "Sobel_U0_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_rows_V_read, "Mat2AXIvideo_U0_img_rows_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_cols_V_read, "Mat2AXIvideo_U0_img_cols_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_0_V_read, "Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_1_V_read, "Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_2_V_read, "Mat2AXIvideo_U0_img_data_stream_2_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din, "Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write, "Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din, "Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write, "Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din, "Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write, "Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din, "Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write, "Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din, "Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write, "Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din, "Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write, "Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din, "Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write, "Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, img_0_rows_V_c_full_n, "img_0_rows_V_c_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c_dout, "img_0_rows_V_c_dout");
    sc_trace(mVcdFile, img_0_rows_V_c_empty_n, "img_0_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c_full_n, "img_0_cols_V_c_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c_dout, "img_0_cols_V_c_dout");
    sc_trace(mVcdFile, img_0_cols_V_c_empty_n, "img_0_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_1_rows_V_c_full_n, "img_1_rows_V_c_full_n");
    sc_trace(mVcdFile, img_1_rows_V_c_dout, "img_1_rows_V_c_dout");
    sc_trace(mVcdFile, img_1_rows_V_c_empty_n, "img_1_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_1_cols_V_c_full_n, "img_1_cols_V_c_full_n");
    sc_trace(mVcdFile, img_1_cols_V_c_dout, "img_1_cols_V_c_dout");
    sc_trace(mVcdFile, img_1_cols_V_c_empty_n, "img_1_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_full_n, "img_0_data_stream_0_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_dout, "img_0_data_stream_0_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_empty_n, "img_0_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_full_n, "img_0_data_stream_1_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_dout, "img_0_data_stream_1_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_empty_n, "img_0_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_2_full_n, "img_0_data_stream_2_full_n");
    sc_trace(mVcdFile, img_0_data_stream_2_dout, "img_0_data_stream_2_dout");
    sc_trace(mVcdFile, img_0_data_stream_2_empty_n, "img_0_data_stream_2_empty_n");
    sc_trace(mVcdFile, img_0_rows_V_c13_full_n, "img_0_rows_V_c13_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c13_dout, "img_0_rows_V_c13_dout");
    sc_trace(mVcdFile, img_0_rows_V_c13_empty_n, "img_0_rows_V_c13_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c14_full_n, "img_0_cols_V_c14_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c14_dout, "img_0_cols_V_c14_dout");
    sc_trace(mVcdFile, img_0_cols_V_c14_empty_n, "img_0_cols_V_c14_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_full_n, "img_1_data_stream_0_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_dout, "img_1_data_stream_0_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_empty_n, "img_1_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_1_full_n, "img_1_data_stream_1_full_n");
    sc_trace(mVcdFile, img_1_data_stream_1_dout, "img_1_data_stream_1_dout");
    sc_trace(mVcdFile, img_1_data_stream_1_empty_n, "img_1_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_2_full_n, "img_1_data_stream_2_full_n");
    sc_trace(mVcdFile, img_1_data_stream_2_dout, "img_1_data_stream_2_dout");
    sc_trace(mVcdFile, img_1_data_stream_2_empty_n, "img_1_data_stream_2_empty_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, start_for_Sobel_U0_din, "start_for_Sobel_U0_din");
    sc_trace(mVcdFile, start_for_Sobel_U0_full_n, "start_for_Sobel_U0_full_n");
    sc_trace(mVcdFile, start_for_Sobel_U0_dout, "start_for_Sobel_U0_dout");
    sc_trace(mVcdFile, start_for_Sobel_U0_empty_n, "start_for_Sobel_U0_empty_n");
    sc_trace(mVcdFile, Sobel_U0_start_full_n, "Sobel_U0_start_full_n");
    sc_trace(mVcdFile, Sobel_U0_start_write, "Sobel_U0_start_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("hls_sobel.hdltvin.dat");
    mHdltvoutHandle.open("hls_sobel.hdltvout.dat");
}

hls_sobel::~hls_sobel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Block_Mat_exit45_pro_U0;
    delete AXIvideo2Mat_U0;
    delete Sobel_U0;
    delete Mat2AXIvideo_U0;
    delete img_0_rows_V_c_U;
    delete img_0_cols_V_c_U;
    delete img_1_rows_V_c_U;
    delete img_1_cols_V_c_U;
    delete img_0_data_stream_0_U;
    delete img_0_data_stream_1_U;
    delete img_0_data_stream_2_U;
    delete img_0_rows_V_c13_U;
    delete img_0_cols_V_c14_U;
    delete img_1_data_stream_0_U;
    delete img_1_data_stream_1_U;
    delete img_1_data_stream_2_U;
    delete start_for_Mat2AXIlbW_U;
    delete start_for_Sobel_U0_U;
}

void hls_sobel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void hls_sobel::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void hls_sobel::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = ap_const_logic_1;
}

void hls_sobel::thread_Block_Mat_exit45_pro_U0_ap_continue() {
    Block_Mat_exit45_pro_U0_ap_continue = ap_const_logic_1;
}

void hls_sobel::thread_Block_Mat_exit45_pro_U0_ap_start() {
    Block_Mat_exit45_pro_U0_ap_start = ap_const_logic_1;
}

void hls_sobel::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void hls_sobel::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void hls_sobel::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void hls_sobel::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void hls_sobel::thread_Sobel_U0_ap_continue() {
    Sobel_U0_ap_continue = ap_const_logic_1;
}

void hls_sobel::thread_Sobel_U0_ap_start() {
    Sobel_U0_ap_start = start_for_Sobel_U0_empty_n.read();
}

void hls_sobel::thread_Sobel_U0_start_full_n() {
    Sobel_U0_start_full_n = ap_const_logic_1;
}

void hls_sobel::thread_Sobel_U0_start_write() {
    Sobel_U0_start_write = ap_const_logic_0;
}

void hls_sobel::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void hls_sobel::thread_input_V_data_V_read() {
    input_V_data_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read.read();
}

void hls_sobel::thread_input_V_dest_V_read() {
    input_V_dest_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read.read();
}

void hls_sobel::thread_input_V_id_V_read() {
    input_V_id_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read.read();
}

void hls_sobel::thread_input_V_keep_V_read() {
    input_V_keep_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read.read();
}

void hls_sobel::thread_input_V_last_V_read() {
    input_V_last_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read.read();
}

void hls_sobel::thread_input_V_strb_V_read() {
    input_V_strb_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read.read();
}

void hls_sobel::thread_input_V_user_V_read() {
    input_V_user_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read.read();
}

void hls_sobel::thread_output_V_data_V_din() {
    output_V_data_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din.read();
}

void hls_sobel::thread_output_V_data_V_write() {
    output_V_data_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write.read();
}

void hls_sobel::thread_output_V_dest_V_din() {
    output_V_dest_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din.read();
}

void hls_sobel::thread_output_V_dest_V_write() {
    output_V_dest_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write.read();
}

void hls_sobel::thread_output_V_id_V_din() {
    output_V_id_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din.read();
}

void hls_sobel::thread_output_V_id_V_write() {
    output_V_id_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write.read();
}

void hls_sobel::thread_output_V_keep_V_din() {
    output_V_keep_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din.read();
}

void hls_sobel::thread_output_V_keep_V_write() {
    output_V_keep_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write.read();
}

void hls_sobel::thread_output_V_last_V_din() {
    output_V_last_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din.read();
}

void hls_sobel::thread_output_V_last_V_write() {
    output_V_last_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write.read();
}

void hls_sobel::thread_output_V_strb_V_din() {
    output_V_strb_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din.read();
}

void hls_sobel::thread_output_V_strb_V_write() {
    output_V_strb_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write.read();
}

void hls_sobel::thread_output_V_user_V_din() {
    output_V_user_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din.read();
}

void hls_sobel::thread_output_V_user_V_write() {
    output_V_user_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write.read();
}

void hls_sobel::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void hls_sobel::thread_start_for_Sobel_U0_din() {
    start_for_Sobel_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void hls_sobel::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"input_V_data_V_dout\" :  \"" << input_V_data_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_data_V_empty_n\" :  \"" << input_V_data_V_empty_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"input_V_data_V_read\" :  \"" << input_V_data_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_keep_V_dout\" :  \"" << input_V_keep_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_keep_V_empty_n\" :  \"" << input_V_keep_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_keep_V_read\" :  \"" << input_V_keep_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_strb_V_dout\" :  \"" << input_V_strb_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_strb_V_empty_n\" :  \"" << input_V_strb_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_strb_V_read\" :  \"" << input_V_strb_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_user_V_dout\" :  \"" << input_V_user_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_user_V_empty_n\" :  \"" << input_V_user_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_user_V_read\" :  \"" << input_V_user_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_last_V_dout\" :  \"" << input_V_last_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_last_V_empty_n\" :  \"" << input_V_last_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_last_V_read\" :  \"" << input_V_last_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_id_V_dout\" :  \"" << input_V_id_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_id_V_empty_n\" :  \"" << input_V_id_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_id_V_read\" :  \"" << input_V_id_V_read.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_dest_V_dout\" :  \"" << input_V_dest_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V_dest_V_empty_n\" :  \"" << input_V_dest_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_V_dest_V_read\" :  \"" << input_V_dest_V_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_data_V_din\" :  \"" << output_V_data_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_data_V_full_n\" :  \"" << output_V_data_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_data_V_write\" :  \"" << output_V_data_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_keep_V_din\" :  \"" << output_V_keep_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_keep_V_full_n\" :  \"" << output_V_keep_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_keep_V_write\" :  \"" << output_V_keep_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_strb_V_din\" :  \"" << output_V_strb_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_strb_V_full_n\" :  \"" << output_V_strb_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_strb_V_write\" :  \"" << output_V_strb_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_user_V_din\" :  \"" << output_V_user_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_user_V_full_n\" :  \"" << output_V_user_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_user_V_write\" :  \"" << output_V_user_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_last_V_din\" :  \"" << output_V_last_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_last_V_full_n\" :  \"" << output_V_last_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_last_V_write\" :  \"" << output_V_last_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_id_V_din\" :  \"" << output_V_id_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_id_V_full_n\" :  \"" << output_V_id_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_id_V_write\" :  \"" << output_V_id_V_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_dest_V_din\" :  \"" << output_V_dest_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"output_V_dest_V_full_n\" :  \"" << output_V_dest_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_V_dest_V_write\" :  \"" << output_V_dest_V_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rows\" :  \"" << rows.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"cols\" :  \"" << cols.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

