// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hls_sobel_HH_
#define _hls_sobel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_Mat_exit45_pro.h"
#include "AXIvideo2Mat.h"
#include "Sobel.h"
#include "Mat2AXIvideo.h"
#include "fifo_w32_d2_A.h"
#include "fifo_w32_d4_A.h"
#include "fifo_w8_d2_A.h"
#include "start_for_Mat2AXIlbW.h"
#include "start_for_Sobel_U0.h"

namespace ap_rtl {

struct hls_sobel : public sc_module {
    // Port declarations 46
    sc_in< sc_lv<24> > input_V_data_V_dout;
    sc_in< sc_logic > input_V_data_V_empty_n;
    sc_out< sc_logic > input_V_data_V_read;
    sc_in< sc_lv<3> > input_V_keep_V_dout;
    sc_in< sc_logic > input_V_keep_V_empty_n;
    sc_out< sc_logic > input_V_keep_V_read;
    sc_in< sc_lv<3> > input_V_strb_V_dout;
    sc_in< sc_logic > input_V_strb_V_empty_n;
    sc_out< sc_logic > input_V_strb_V_read;
    sc_in< sc_lv<1> > input_V_user_V_dout;
    sc_in< sc_logic > input_V_user_V_empty_n;
    sc_out< sc_logic > input_V_user_V_read;
    sc_in< sc_lv<1> > input_V_last_V_dout;
    sc_in< sc_logic > input_V_last_V_empty_n;
    sc_out< sc_logic > input_V_last_V_read;
    sc_in< sc_lv<1> > input_V_id_V_dout;
    sc_in< sc_logic > input_V_id_V_empty_n;
    sc_out< sc_logic > input_V_id_V_read;
    sc_in< sc_lv<1> > input_V_dest_V_dout;
    sc_in< sc_logic > input_V_dest_V_empty_n;
    sc_out< sc_logic > input_V_dest_V_read;
    sc_out< sc_lv<24> > output_V_data_V_din;
    sc_in< sc_logic > output_V_data_V_full_n;
    sc_out< sc_logic > output_V_data_V_write;
    sc_out< sc_lv<3> > output_V_keep_V_din;
    sc_in< sc_logic > output_V_keep_V_full_n;
    sc_out< sc_logic > output_V_keep_V_write;
    sc_out< sc_lv<3> > output_V_strb_V_din;
    sc_in< sc_logic > output_V_strb_V_full_n;
    sc_out< sc_logic > output_V_strb_V_write;
    sc_out< sc_lv<1> > output_V_user_V_din;
    sc_in< sc_logic > output_V_user_V_full_n;
    sc_out< sc_logic > output_V_user_V_write;
    sc_out< sc_lv<1> > output_V_last_V_din;
    sc_in< sc_logic > output_V_last_V_full_n;
    sc_out< sc_logic > output_V_last_V_write;
    sc_out< sc_lv<1> > output_V_id_V_din;
    sc_in< sc_logic > output_V_id_V_full_n;
    sc_out< sc_logic > output_V_id_V_write;
    sc_out< sc_lv<1> > output_V_dest_V_din;
    sc_in< sc_logic > output_V_dest_V_full_n;
    sc_out< sc_logic > output_V_dest_V_write;
    sc_in< sc_lv<32> > rows;
    sc_in< sc_lv<32> > cols;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    hls_sobel(sc_module_name name);
    SC_HAS_PROCESS(hls_sobel);

    ~hls_sobel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Block_Mat_exit45_pro* Block_Mat_exit45_pro_U0;
    AXIvideo2Mat* AXIvideo2Mat_U0;
    Sobel* Sobel_U0;
    Mat2AXIvideo* Mat2AXIvideo_U0;
    fifo_w32_d2_A* img_0_rows_V_c_U;
    fifo_w32_d2_A* img_0_cols_V_c_U;
    fifo_w32_d4_A* img_1_rows_V_c_U;
    fifo_w32_d4_A* img_1_cols_V_c_U;
    fifo_w8_d2_A* img_0_data_stream_0_U;
    fifo_w8_d2_A* img_0_data_stream_1_U;
    fifo_w8_d2_A* img_0_data_stream_2_U;
    fifo_w32_d2_A* img_0_rows_V_c13_U;
    fifo_w32_d2_A* img_0_cols_V_c14_U;
    fifo_w8_d2_A* img_1_data_stream_0_U;
    fifo_w8_d2_A* img_1_data_stream_1_U;
    fifo_w8_d2_A* img_1_data_stream_2_U;
    start_for_Mat2AXIlbW* start_for_Mat2AXIlbW_U;
    start_for_Sobel_U0* start_for_Sobel_U0_U;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_ap_start;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_ap_done;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_ap_continue;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_ap_idle;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_ap_ready;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_start_out;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_start_write;
    sc_signal< sc_lv<32> > Block_Mat_exit45_pro_U0_img_0_rows_V_out_din;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_img_0_rows_V_out_write;
    sc_signal< sc_lv<32> > Block_Mat_exit45_pro_U0_img_0_cols_V_out_din;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_img_0_cols_V_out_write;
    sc_signal< sc_lv<32> > Block_Mat_exit45_pro_U0_img_1_rows_V_out_din;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_img_1_rows_V_out_write;
    sc_signal< sc_lv<32> > Block_Mat_exit45_pro_U0_img_1_cols_V_out_din;
    sc_signal< sc_logic > Block_Mat_exit45_pro_U0_img_1_cols_V_out_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_start;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_done;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_continue;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_idle;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_out;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_read;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_0_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_0_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_1_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_1_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_2_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_2_V_write;
    sc_signal< sc_lv<32> > AXIvideo2Mat_U0_img_rows_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_out_write;
    sc_signal< sc_lv<32> > AXIvideo2Mat_U0_img_cols_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_out_write;
    sc_signal< sc_logic > Sobel_U0_ap_start;
    sc_signal< sc_logic > Sobel_U0_ap_done;
    sc_signal< sc_logic > Sobel_U0_ap_continue;
    sc_signal< sc_logic > Sobel_U0_ap_idle;
    sc_signal< sc_logic > Sobel_U0_ap_ready;
    sc_signal< sc_logic > Sobel_U0_p_src_rows_V_read;
    sc_signal< sc_logic > Sobel_U0_p_src_cols_V_read;
    sc_signal< sc_logic > Sobel_U0_p_src_data_stream_0_V_read;
    sc_signal< sc_logic > Sobel_U0_p_src_data_stream_1_V_read;
    sc_signal< sc_logic > Sobel_U0_p_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > Sobel_U0_p_dst_data_stream_0_V_din;
    sc_signal< sc_logic > Sobel_U0_p_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > Sobel_U0_p_dst_data_stream_1_V_din;
    sc_signal< sc_logic > Sobel_U0_p_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > Sobel_U0_p_dst_data_stream_2_V_din;
    sc_signal< sc_logic > Sobel_U0_p_dst_data_stream_2_V_write;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_start;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_done;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_continue;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_idle;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_ready;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_rows_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_cols_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_0_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_1_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_2_V_read;
    sc_signal< sc_lv<24> > Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din;
    sc_signal< sc_logic > Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din;
    sc_signal< sc_logic > Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din;
    sc_signal< sc_logic > Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din;
    sc_signal< sc_logic > Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din;
    sc_signal< sc_logic > Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din;
    sc_signal< sc_logic > Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din;
    sc_signal< sc_logic > Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > img_0_rows_V_c_full_n;
    sc_signal< sc_lv<32> > img_0_rows_V_c_dout;
    sc_signal< sc_logic > img_0_rows_V_c_empty_n;
    sc_signal< sc_logic > img_0_cols_V_c_full_n;
    sc_signal< sc_lv<32> > img_0_cols_V_c_dout;
    sc_signal< sc_logic > img_0_cols_V_c_empty_n;
    sc_signal< sc_logic > img_1_rows_V_c_full_n;
    sc_signal< sc_lv<32> > img_1_rows_V_c_dout;
    sc_signal< sc_logic > img_1_rows_V_c_empty_n;
    sc_signal< sc_logic > img_1_cols_V_c_full_n;
    sc_signal< sc_lv<32> > img_1_cols_V_c_dout;
    sc_signal< sc_logic > img_1_cols_V_c_empty_n;
    sc_signal< sc_logic > img_0_data_stream_0_full_n;
    sc_signal< sc_lv<8> > img_0_data_stream_0_dout;
    sc_signal< sc_logic > img_0_data_stream_0_empty_n;
    sc_signal< sc_logic > img_0_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_0_data_stream_1_dout;
    sc_signal< sc_logic > img_0_data_stream_1_empty_n;
    sc_signal< sc_logic > img_0_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_0_data_stream_2_dout;
    sc_signal< sc_logic > img_0_data_stream_2_empty_n;
    sc_signal< sc_logic > img_0_rows_V_c13_full_n;
    sc_signal< sc_lv<32> > img_0_rows_V_c13_dout;
    sc_signal< sc_logic > img_0_rows_V_c13_empty_n;
    sc_signal< sc_logic > img_0_cols_V_c14_full_n;
    sc_signal< sc_lv<32> > img_0_cols_V_c14_dout;
    sc_signal< sc_logic > img_0_cols_V_c14_empty_n;
    sc_signal< sc_logic > img_1_data_stream_0_full_n;
    sc_signal< sc_lv<8> > img_1_data_stream_0_dout;
    sc_signal< sc_logic > img_1_data_stream_0_empty_n;
    sc_signal< sc_logic > img_1_data_stream_1_full_n;
    sc_signal< sc_lv<8> > img_1_data_stream_1_dout;
    sc_signal< sc_logic > img_1_data_stream_1_empty_n;
    sc_signal< sc_logic > img_1_data_stream_2_full_n;
    sc_signal< sc_lv<8> > img_1_data_stream_2_dout;
    sc_signal< sc_logic > img_1_data_stream_2_empty_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_din;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_dout;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Sobel_U0_din;
    sc_signal< sc_logic > start_for_Sobel_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Sobel_U0_dout;
    sc_signal< sc_logic > start_for_Sobel_U0_empty_n;
    sc_signal< sc_logic > Sobel_U0_start_full_n;
    sc_signal< sc_logic > Sobel_U0_start_write;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_full_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_write;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_AXIvideo2Mat_U0_ap_continue();
    void thread_AXIvideo2Mat_U0_ap_start();
    void thread_Block_Mat_exit45_pro_U0_ap_continue();
    void thread_Block_Mat_exit45_pro_U0_ap_start();
    void thread_Mat2AXIvideo_U0_ap_continue();
    void thread_Mat2AXIvideo_U0_ap_start();
    void thread_Mat2AXIvideo_U0_start_full_n();
    void thread_Mat2AXIvideo_U0_start_write();
    void thread_Sobel_U0_ap_continue();
    void thread_Sobel_U0_ap_start();
    void thread_Sobel_U0_start_full_n();
    void thread_Sobel_U0_start_write();
    void thread_ap_sync_continue();
    void thread_input_V_data_V_read();
    void thread_input_V_dest_V_read();
    void thread_input_V_id_V_read();
    void thread_input_V_keep_V_read();
    void thread_input_V_last_V_read();
    void thread_input_V_strb_V_read();
    void thread_input_V_user_V_read();
    void thread_output_V_data_V_din();
    void thread_output_V_data_V_write();
    void thread_output_V_dest_V_din();
    void thread_output_V_dest_V_write();
    void thread_output_V_id_V_din();
    void thread_output_V_id_V_write();
    void thread_output_V_keep_V_din();
    void thread_output_V_keep_V_write();
    void thread_output_V_last_V_din();
    void thread_output_V_last_V_write();
    void thread_output_V_strb_V_din();
    void thread_output_V_strb_V_write();
    void thread_output_V_user_V_din();
    void thread_output_V_user_V_write();
    void thread_start_for_Mat2AXIvideo_U0_din();
    void thread_start_for_Sobel_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
